#!/usr/bin/env python3
"""Generate the literal Lean manifest for the 120 RS62 checkpoint segments.

This is an artifact generator, not a proof.  The generated literals are
accepted only through the separately compiled configuration and segment
receipts.  No production range is evaluated by Lean.
"""

from __future__ import annotations

import argparse
import math
from pathlib import Path
import re


def primes_below(limit: int) -> list[int]:
    sieve = bytearray(b"\x01") * limit
    sieve[:2] = b"\x00\x00"
    for p in range(2, math.isqrt(limit - 1) + 1):
        if sieve[p]:
            sieve[p * p:limit:p] = b"\x00" * (
                ((limit - 1 - p * p) // p) + 1
            )
    return [p for p in range(2, limit) if sieve[p]]


def wrapped_nats(values: list[int], indent: str = "  ") -> str:
    lines: list[str] = []
    for start in range(0, len(values), 16):
        suffix = "," if start + 16 < len(values) else ""
        lines.append(indent + ", ".join(map(str, values[start:start + 16])) + suffix)
    return "\n".join(lines)


def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--source", required=True, type=Path)
    parser.add_argument("--output", required=True, type=Path)
    args = parser.parse_args()

    checkpoints = [
        tuple(map(int, values))
        for values in re.findall(
            r"\| r(\d{3}) : RangeCheckpoint (\d+) (\d+) (\d+)",
            args.source.read_text(encoding="utf-8"),
        )
    ]
    if len(checkpoints) != 120:
        raise SystemExit(f"expected 120 checkpoints, found {len(checkpoints)}")

    previous_fuel = 99_999_900
    lower = 386_481_147_529_431
    upper = 386_487_029_388_140
    rows: list[str] = []
    for index, fuel, next_lower, next_upper in checkpoints:
        lo = previous_fuel + 101
        seg_len = fuel - previous_fuel
        hi = lo + seg_len - 1
        root_cap = math.isqrt(hi) + 1
        # The verified root-store gate is inclusive at `rootCap`.  The
        # ceiling-square cap is one above `isqrt(hi)` for nonsquares, so its
        # final prime is mathematically unnecessary but still collected by
        # the production program.  The table and budget must therefore also
        # include it whenever that ceiling happens to be prime.
        primes = primes_below(root_cap + 1)
        mark_steps = sum(seg_len // p + 2 for p in primes)
        rows.append(
            "  { "
            f"idx := {index}, fuel := {fuel}, lo := {lo}, segLen := {seg_len}, "
            f"rootCap := {root_cap}, mainCount := {len(primes)}, "
            f"markSteps := {mark_steps}, SL := {lower}, SU := {upper}, "
            f"lower := {next_lower}, upper := {next_upper} "
            "}"
        )
        previous_fuel = fuel
        lower, upper = next_lower, next_upper

    text = f'''import LeanCompCert.Ports.RS62SegmentedPrimeMask
import LeanCompCert.Ports.CanonicalPrimeTable

/-!
# Literal manifest for the 120 RS62 checkpoint segments

Generated by `bench/GenerateRS62CheckpointManifest.py` from the source
`RangeCheckpoint` constructors.  These are configuration literals, not
proofs; compiled receipts and their refinement theorems validate them.
-/

namespace LeanCompCert.Ports.RS62CheckpointManifestData

open LeanCompCert.Ports.ArraySegSieve

structure Row where
  idx : Nat
  fuel : Nat
  lo : Nat
  segLen : Nat
  rootCap : Nat
  mainCount : Nat
  markSteps : Nat
  SL : Nat
  SU : Nat
  lower : Nat
  upper : Nat
  deriving Repr, DecidableEq

/-- Canonical source specification for the bootstrap table. Its exact prime
table invariant is structural, so no closed primality sweep is evaluated by
Lean to justify the table. -/
def bootstrapPrimes : List Nat :=
  LeanCompCert.Ports.CanonicalPrimeTable.primesThrough 1000

def Row.cfg (row : Row) : Cfg := {{
  lo := row.lo
  segLen := row.segLen
  segCount := 1
  rootCount := 1
  bootPrimes := bootstrapPrimes
  mainCount := row.mainCount
  rootCap := row.rootCap
  markSteps := row.markSteps
}}

def rows : List Row := [
{(',\n'.join(rows))}
]

theorem rows_length : rows.length = 120 := by rfl

end LeanCompCert.Ports.RS62CheckpointManifestData
'''
    args.output.write_text(text, encoding="utf-8")


if __name__ == "__main__":
    main()
