import LeanCompCert.Testing.VerifiedDecide
import LeanCompCert.Testing.MertensCertificate
import LeanCompCert.Testing.WideMertensCertificate
import LeanCompCert.Testing.SquarefreeMertensCertificate
import LeanCompCert.Testing.ReflectedCertificate
import LeanCompCert.Testing.FixedPointCertificate
import LeanCompCert.Testing.PackedCoverageCertificate
import LeanCompCert.Verified.Limb
import LeanCompCert.Verified.EarlyExit
import LeanCompCert.Verified.Rolled
import LeanCompCert.Verified.GcdEquiv
import LeanCompCert.Verified.SqrtEquiv
import LeanCompCert.Verified.SignedLimb
import LeanCompCert.Verified.Log2Fixed
import LeanCompCert.Verified.LogFixed
import LeanCompCert.Verified.Sieve
import LeanCompCert.Verified.Dyadic
import LeanCompCert.Verified.MulWide
import LeanCompCert.Verified.Frontend
import LeanCompCert.Verified.ArrayState
import LeanCompCert.Verified.MemFragment
import LeanCompCert.Verified.ArrayBridge
import LeanCompCert.Verified.ArrayRolled
import LeanCompCert.Verified.Packed
import LeanCompCert.Verified.PackedTransfer
import LeanCompCert.Verified.ListFold
import LeanCompCert.Verified.PackedSieve
import LeanCompCert.Verified.Segment
import LeanCompCert.Verified.FoldBridge
import LeanCompCert.Verified.Prop1224Margin
import LeanCompCert.Ports.Prop1224Cell
import LeanCompCert.Ports.Prop1224Row
import LeanCompCert.Ports.RS62Increments
import LeanCompCert.Ports.RS62LoopE
import LeanCompCert.Ports.TGSieve
import LeanCompCert.Ports.TGLadder
import LeanCompCert.Verified.Montgomery
import LeanCompCert.Verified.Mont2
import LeanCompCert.Verified.Straight
import LeanCompCert.Verified.InstrBlock
import LeanCompCert.Ports.TGProth
import LeanCompCert.Ports.ArrayMobius
import LeanCompCert.Testing.DirichletLadderCertificate
import LeanCompCert.Ports.ArraySegSieve
import LeanCompCert.Ports.ArraySegMobiusInit
import LeanCompCert.Ports.ArraySegMobiusSignal
import LeanCompCert.Ports.ArraySegMobiusMarkCore
import LeanCompCert.Ports.ArraySegMobiusMarkStart
import LeanCompCert.Ports.ArraySegMobiusCursorCore
import LeanCompCert.Ports.ArraySegMobiusCursorPrefix
import LeanCompCert.Ports.ArraySegMobiusSelector
import LeanCompCert.Ports.ArraySegMobiusCursorSignal
import LeanCompCert.Ports.ArraySegMobiusWindow
import LeanCompCert.Ports.ArraySegMobiusClear
import LeanCompCert.Ports.ArraySegMobiusRootWrite
import LeanCompCert.Ports.ArraySegMobiusPrimeInvariant
import LeanCompCert.Ports.ArraySegMobiusPrimeTable
import LeanCompCert.Ports.ArraySegMobiusPrimeTableRep
import LeanCompCert.Ports.ArraySegMobiusRootCellFold
import LeanCompCert.Ports.ArraySegMobiusRootSchedule
import LeanCompCert.Ports.ArraySegMobiusCursorModel
import LeanCompCert.Ports.ArraySegMobiusScheduleFold
import LeanCompCert.Ports.ArraySegMobiusCellRep
import LeanCompCert.Ports.ArraySegMobiusAccumulation
import LeanCompCert.Ports.ArraySegMobiusRootAccumulation
import LeanCompCert.Ports.ArraySegMobiusRootPrefix
import LeanCompCert.Ports.ArraySegMobiusRootMarkFold
import LeanCompCert.Ports.ArraySegMobiusIndexedRun
import LeanCompCert.Ports.ArraySegMobiusIndexedRootPrefix
import LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv
import LeanCompCert.Ports.ArraySegMobiusIndexedRootMixed
import LeanCompCert.Ports.ArraySegMobiusIndexedRootWindows
import LeanCompCert.Ports.ArraySegMobiusIndexedMain
import LeanCompCert.Ports.ArraySegMobiusIndexedRootOuter
import LeanCompCert.Ports.ArraySegMobiusIndexedProgram
import LeanCompCert.Ports.ArraySegMobiusIndexedFull
import LeanCompCert.Ports.ArraySegMobiusResidueFrame
import LeanCompCert.Ports.ArraySegMobiusResidueFold
import LeanCompCert.Ports.ArraySegMobiusIndexedSignal
import LeanCompCert.Ports.ArraySegMobiusIdleSignal
import LeanCompCert.Ports.ArraySegMobiusMarkProgress
import LeanCompCert.Ports.MobiusResidueRealisation
import LeanCompCert.Ports.MobiusResidueWindow
import LeanCompCert.Ports.MobiusResidueScalar
import LeanCompCert.Ports.MobiusResidueTrial
import LeanCompCert.Ports.MobiusResidueTrialWindow
import LeanCompCert.Ports.MobiusExtremaScalar
import LeanCompCert.Ports.MobiusExtremaTrial
import LeanCompCert.Ports.MobiusExtremaTrialWindow
import LeanCompCert.Ports.LogFixPort
import LeanCompCert.Verified.AddWide
import LeanCompCert.Verified.LogAccum
import LeanCompCert.Ports.AddWidePort
import LeanCompCert.Ports.PsiSegSieve
import LeanCompCert.Ports.R2SegSieve
import LeanCompCert.Ports.CDEMAbelScan
import LeanCompCert.Testing.AbelScanCertificate
import LeanCompCert.Testing.ArraySegCertificate
import LeanCompCert.Verified.DyadicBisect
import LeanCompCert.Ports.A36Bisect
import LeanCompCert.Ports.A36BisectProgram
import LeanCompCert.Verified.ExpFixed
import LeanCompCert.Ports.ExpFixPort
import LeanCompCert.Verified.ArrayFoldBridge
import LeanCompCert.Ports.RamareMStar140MDenote
import LeanCompCert.Verified.Algorithm.ArrayBridge
import LeanCompCert.Ports.ArraySieveCount
import LeanCompCert.Ports.ArrayMobiusDenotation
import LeanCompCert.Attest
import LeanCompCert.Attest.LedgerReport
import LeanCompCert.Testing.AlgorithmProof
import LeanCompCertTests.Attest


/-!
Axiom-audit gate (M7): prints the axiom dependencies of every certificate
theorem. The acceptance script enforces an allowlist — it fails if any
axiom outside `propext`/`Classical.choice`/`Quot.sound` appears, which
covers the native-evaluation axioms (`ofReduceBool`/`ofReduceNat`,
`Lean.trustCompiler`) as well as `sorryAx` and bespoke axioms.

New certificates must be added to this list by hand; a misspelled name
fails elaboration, so an entry cannot silently audit nothing.
-/
#print axioms LeanCompCert.Verified.Computation.result_preserved
#print axioms LeanCompCert.Testing.VerifiedDecide.source_computation_returns_42
#print axioms LeanCompCert.Testing.MertensCertificate.referenceSum_eq
#print axioms LeanCompCert.Testing.WideMertensCertificate.referenceSum_eq
#print axioms LeanCompCert.Testing.SquarefreeMertensCertificate.referenceSum_eq
#print axioms LeanCompCert.Testing.ReflectedCertificate.referenceSum_eq
#print axioms LeanCompCert.Testing.FixedPointCertificate.referenceSum_eq
#print axioms LeanCompCert.Verified.Reflect.Program.evalCC_compile
#print axioms LeanCompCert.Verified.Reflect.toComputation_returns
#print axioms LeanCompCert.Verified.Packed.lane_poke_self
#print axioms LeanCompCert.Verified.Packed.lane_poke_ne
#print axioms LeanCompCert.Verified.Packed.lane_lt
#print axioms LeanCompCert.Verified.Packed.laneState_poke
#print axioms LeanCompCert.Verified.Packed.testBit_repunit
#print axioms LeanCompCert.Verified.Packed.testBit_classMask
#print axioms LeanCompCert.Verified.Packed.testBit_orAll
#print axioms LeanCompCert.Verified.Packed.covers_iff
#print axioms LeanCompCert.Verified.Packed.mem_class_of_covers_classUnion
#print axioms LeanCompCert.Verified.Packed.laneState_poke_eq_set
#print axioms LeanCompCert.Verified.Packed.denoteInstrsPacked_eq
#print axioms LeanCompCert.Verified.Packed.Program.denotePacked_eq_denote
#print axioms LeanCompCert.Verified.Packed.arrState_poke_eq_writeArr
#print axioms LeanCompCert.Verified.ListFold.foldl_guard
#print axioms LeanCompCert.Verified.ListFold.foldl_table
#print axioms LeanCompCert.Verified.ListFold.foldl_of_certifies
#print axioms LeanCompCert.Verified.ListFold.evalCCSequence_foldTraceList
#print axioms LeanCompCert.Verified.ListFold.LProgram.evalCC_compile
#print axioms LeanCompCert.Testing.PackedCoverageCertificate.coverage_accepted
#print axioms LeanCompCert.Testing.PackedCoverageCertificate.covering_system_covers
#print axioms LeanCompCert.Verified.PackedSieve.exists_prime_dvd
#print axioms LeanCompCert.Verified.PackedSieve.exists_prime_factor_le_sqrt
#print axioms LeanCompCert.Verified.PackedSieve.isPrime_iff_bounded
#print axioms LeanCompCert.Verified.PackedSieve.testBit_multiplesMask
#print axioms LeanCompCert.Verified.PackedSieve.testBit_compositeBits
#print axioms LeanCompCert.Verified.PackedSieve.testBit_compositeBits_eq_false_iff
#print axioms LeanCompCert.Verified.PackedSieve.sieveList_eq_filter
#print axioms LeanCompCert.Verified.PackedSieve.PrimeBase.step
#print axioms LeanCompCert.Verified.PackedSieve.PrimeBase.ofTrialDivision
#print axioms LeanCompCert.Verified.Limb.mulLimbs_val
#print axioms LeanCompCert.Verified.EarlyExit.foldP_accepts_iff
#print axioms LeanCompCert.Verified.Reflect.evalCCSequence_var_eq_lit
#print axioms LeanCompCert.Verified.Reflect.lit_preserves_counter
#print axioms LeanCompCert.Verified.Limb.divModMSB_val
#print axioms LeanCompCert.Verified.Reflect.rolledTrace_eq_augmented
#print axioms LeanCompCert.Verified.Gcd.gcdFuel_eq
#print axioms LeanCompCert.Verified.SqrtEquiv.isqrt_eq
#print axioms LeanCompCert.Verified.SignedLimb.add_val
#print axioms LeanCompCert.Verified.Log2Fixed.log2Fixed_eq
#print axioms LeanCompCert.Verified.Sieve.spfFixed_eq_leastFactor
#print axioms LeanCompCert.Verified.Dyadic.mulLo_le
#print axioms LeanCompCert.Verified.MulWide.hl_spec
#print axioms LeanCompCert.Verified.Frontend.compileExpr_correct
#print axioms LeanCompCert.Verified.ArrayState.sieveSweep_cell
-- M9: the array fold bridge, and the first array port with a proved denotation
#print axioms LeanCompCert.Verified.ArrayFoldBridge.denoteAInstrs_eq_arun
#print axioms LeanCompCert.Verified.ArrayFoldBridge.eq_astep_of_denoteAInstr_eq_some
#print axioms LeanCompCert.Verified.ArrayFoldBridge.eq_arun_of_denoteAInstrs_eq_some
#print axioms LeanCompCert.Verified.ArrayFoldBridge.eq_foldl_arun_of_foldlM_denote_eq_some
#print axioms LeanCompCert.Verified.ArrayFoldBridge.AProgram.output_eq_arun_of_denote_eq_some
#print axioms LeanCompCert.Verified.ArrayFoldBridge.AProgram.denote_eq_foldl_mem
#print axioms LeanCompCert.Verified.ArrayFoldBridge.AProgram.denote_eq_obs_foldl_mem
#print axioms LeanCompCert.Verified.ArrayFoldBridge.foldl_count_mod
#print axioms LeanCompCert.Ports.ArraySieveCount.body_spec
#print axioms LeanCompCert.Ports.ArraySieveCount.sieveCountProgram_denote
#print axioms LeanCompCert.Ports.ArraySieveCount.sieveCountProgram_compiled
#print axioms LeanCompCert.Ports.ArraySieveCount.leastFactor_eq_self_iff
-- M10: the array refinement combinator, and the two arrows for an array port
#print axioms LeanCompCert.Verified.ArrayFoldBridge.AllDefined_append
#print axioms LeanCompCert.Verified.ArrayFoldBridge.or_one_mod
#print axioms LeanCompCert.Verified.Algorithm.ArrayLoop.denote
#print axioms LeanCompCert.Verified.Algorithm.AProgramRefinement.ofDenotationOn
#print axioms LeanCompCert.Verified.Algorithm.AProgramRefinement.ofArrayLoopOn
#print axioms LeanCompCert.Verified.Algorithm.trace_value_unique
#print axioms LeanCompCert.Ports.ArraySieveCount.reference_sound
#print axioms LeanCompCert.Ports.ArraySieveCount.example_result
#print axioms LeanCompCert.Ports.ArrayMobiusDenotation.body_defined
#print axioms LeanCompCert.Ports.ArrayMobiusDenotation.layoutOk
#print axioms LeanCompCert.Verified.MemFragment.lowerMSequence_correct
-- Tail-recursive trace lowering: the two equations the correctness proofs use
#print axioms LeanCompCert.Verified.MemFragment.lowerMAux_eq
#print axioms LeanCompCert.Verified.MemFragment.lowerMSequence_nil
#print axioms LeanCompCert.Verified.MemFragment.lowerMSequence_cons
#print axioms LeanCompCert.Proof.lowerSequenceAux_eq
#print axioms LeanCompCert.Proof.lowerSequence_nil
#print axioms LeanCompCert.Proof.lowerSequence_cons
#print axioms LeanCompCert.Proof.lowerSequence_correct
#print axioms LeanCompCert.Proof.lowerSequence_append
#print axioms LeanCompCert.Proof.lowerSequence_is_lowerInstructions
-- M6: the array bridge (AProgram -> CCIR -> generated C)
#print axioms LeanCompCert.Verified.ArrayState.evalMCCSequence_straight
#print axioms LeanCompCert.Verified.ArrayState.evalCCStraight_frame
#print axioms LeanCompCert.Verified.ArrayState.cellAddr_inj
#print axioms LeanCompCert.Verified.ArrayState.compileAInstr_correct
#print axioms LeanCompCert.Verified.ArrayState.compileAInstrs_correct
#print axioms LeanCompCert.Verified.ArrayState.foldBodyA_correct
#print axioms LeanCompCert.Verified.ArrayState.apreamble_correct
#print axioms LeanCompCert.Verified.ArrayState.AProgram.evalCC_compile
#print axioms LeanCompCert.Verified.ArrayState.AProgram.evalC_compile
#print axioms LeanCompCert.Verified.ArrayState.evalMCCSequence_var_eq_lit
#print axioms LeanCompCert.Verified.ArrayState.rolledTraceM_eq_literalSegM
#print axioms LeanCompCert.Verified.ArrayState.rolledTraceM_eq_foldTraceM
-- M6 load: the segmented Mobius sieve in the array fragment
#print axioms LeanCompCert.Ports.ArrayMobius.mobiusProgram_wf
#print axioms LeanCompCert.Ports.ArrayMobius.mobiusProgram_compiled

-- Generic segmentation lever
#print axioms LeanCompCert.Verified.Segment.foldl_range'_split
#print axioms LeanCompCert.Verified.Segment.foldl_range'_of_chain
#print axioms LeanCompCert.Verified.Segment.foldl_range_of_chain
-- Generic program/fold bridge
#print axioms LeanCompCert.Verified.FoldBridge.foldlM_body_eq_foldl
#print axioms LeanCompCert.Verified.FoldBridge.foldl_obs
#print axioms LeanCompCert.Verified.FoldBridge.LProgram.denote_eq_foldl
#print axioms LeanCompCert.Verified.FoldBridge.Program.denote_eq_foldl
#print axioms LeanCompCert.Verified.FoldBridge.Program.denote_eq_scalar_foldl
-- RS62 ladder port
#print axioms LeanCompCert.Ports.RS62.div_sub_eq_sub_ceilDiv
#print axioms LeanCompCert.Ports.RS62.incL_eq_wordSafe
#print axioms LeanCompCert.Ports.RS62.incU_eq_wordSafe
#print axioms LeanCompCert.Ports.RS62.loopE_eq_foldl
#print axioms LeanCompCert.Ports.RS62.loopE_of_chain
#print axioms LeanCompCert.Ports.RS62.loopE_eq_filter_foldl
#print axioms LeanCompCert.Ports.RS62.loopE_eq_word

-- Helfgott--Platt Goldbach ladder port: stage (a), the progression sieve
#print axioms LeanCompCert.Ports.TGSieve.dvd_of_odd_dvd_two_mul
#print axioms LeanCompCert.Ports.TGSieve.dvd_of_odd_dvd_two_pow_mul
#print axioms LeanCompCert.Ports.TGSieve.dvd_proth_iff
#print axioms LeanCompCert.Ports.TGSieve.sieveTable_valid
#print axioms LeanCompCert.Ports.TGSieve.hitCount_eq_zero_iff
#print axioms LeanCompCert.Ports.TGSieve.bodyInstrs_wf
#print axioms LeanCompCert.Ports.TGSieve.sieveProgram_wf
#print axioms LeanCompCert.Ports.TGSieve.sieveProgram_denote_mod
#print axioms LeanCompCert.Ports.TGSieve.sieveProgram_denote
-- stage (c), ladder assembly
#print axioms LeanCompCert.Ports.TGLadder.gap_le_iff
#print axioms LeanCompCert.Ports.TGLadder.covers
#print axioms LeanCompCert.Ports.TGLadder.lastNum_runningK
#print axioms LeanCompCert.Ports.TGLadder.gapChain_of_deltas
#print axioms LeanCompCert.Ports.TGLadder.covers_of_deltas
#print axioms LeanCompCert.Ports.TGLadder.finalK_eq
#print axioms LeanCompCert.Ports.TGLadder.ladderProgram_wf
#print axioms LeanCompCert.Ports.TGLadder.ladderProgram_denote_mod
#print axioms LeanCompCert.Ports.TGLadder.ladderProgram_denote
#print axioms LeanCompCert.Ports.TGLadder.covers_of_accepts

-- Verified multi-precision modular arithmetic: the Nat-level algebra
#print axioms LeanCompCert.Verified.Montgomery.cancel_B_pow
#print axioms LeanCompCert.Verified.Montgomery.redcStep_mul
#print axioms LeanCompCert.Verified.Montgomery.redcIter_mul
#print axioms LeanCompCert.Verified.Montgomery.redcIter_lt
#print axioms LeanCompCert.Verified.Montgomery.montMul_lt
#print axioms LeanCompCert.Verified.Montgomery.montMul_spec
#print axioms LeanCompCert.Verified.Montgomery.montMul_rep
#print axioms LeanCompCert.Verified.Montgomery.montPow_rep
#print axioms LeanCompCert.Verified.Montgomery.montExp_spec
-- ... its two-limb realization in the 64-bit instruction set
#print axioms LeanCompCert.Verified.Mont2.addcW_eq
#print axioms LeanCompCert.Verified.Mont2.sbbcW_eq
#print axioms LeanCompCert.Verified.Mont2.hlW_eq
#print axioms LeanCompCert.Verified.Mont2.hlW_spec
#print axioms LeanCompCert.Verified.Mont2.mul2_val
#print axioms LeanCompCert.Verified.Mont2.redcStep2_val
#print axioms LeanCompCert.Verified.Mont2.condSub2_val
#print axioms LeanCompCert.Verified.Mont2.montMul2_val
#print axioms LeanCompCert.Verified.Mont2.dbl2_val
#print axioms LeanCompCert.Verified.Mont2.dblIter_val
-- Straight-line block layers
#print axioms LeanCompCert.Verified.Straight.block_correct
#print axioms LeanCompCert.Verified.Straight.block_wf
#print axioms LeanCompCert.Verified.InstrBlock.srun_correct
#print axioms LeanCompCert.Verified.InstrBlock.srun_append
#print axioms LeanCompCert.Verified.InstrBlock.srun_untouched
#print axioms LeanCompCert.Verified.InstrBlock.srun_lt
-- Helfgott--Platt Goldbach ladder port: stage (b), the Proth test
#print axioms LeanCompCert.Ports.TGProth.prothProgram_denote_fold
#print axioms LeanCompCert.Ports.TGProth.prothProgram_wf
#print axioms LeanCompCert.Ports.TGProth.body_step
#print axioms LeanCompCert.Ports.TGProth.prothProgram_denote

-- Offset segmented sieve: the residues of the reduced cite families
#print axioms LeanCompCert.Ports.ArraySegSieve.forall_wf_of_all
#print axioms LeanCompCert.Ports.ArraySegSieve.coreBody_all
#print axioms LeanCompCert.Ports.ArraySegSieve.coreInit_all
#print axioms LeanCompCert.Ports.ArraySegSieve.segProgram_wf
#print axioms LeanCompCert.Ports.ArraySegSieve.mertensProgram_wf
#print axioms LeanCompCert.Ports.ArraySegSieve.mobiusProgram_wf
#print axioms LeanCompCert.Ports.ArraySegSieve.mertensProgram_compiled
#print axioms LeanCompCert.Ports.ArraySegSieve.mobiusProgram_compiled
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_coreInit_terminal_guard
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.coreInit_terminal_guard_pos
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_initTriple
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_bootInitFrom_tablePrefix
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_initTail_frame
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_coreInit_tableRep
-- the per-integer threshold variant
#print axioms LeanCompCert.Ports.ArraySegSieve.mertensLiveResidue_all
#print axioms LeanCompCert.Ports.ArraySegSieve.mertensLiveInit_all
#print axioms LeanCompCert.Ports.ArraySegSieve.mertensLiveEpilogue_all
#print axioms LeanCompCert.Ports.ArraySegSieve.mertensLiveProgram_wf
#print axioms LeanCompCert.Ports.ArraySegSieve.mertensLiveProgram_compiled
-- the per-integer Sum mu(m)/m variant, on a two-limb accumulator
#print axioms LeanCompCert.Ports.ArraySegSieve.mobiusLiveResidue_all
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.mobiusLiveResidue_denote
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.accStep_mu
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.ResInv.step
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.ResInv.changeFunction
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.resFold_range_eq_resRun
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.resRun_inv
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.resStep_viol_eq
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.resRun_zero_all_pass
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.ResInv.hiSmall
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.stepAbs_exact_bound
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.StepPass.sound
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.resRun_zero_sound
#print axioms LeanCompCert.Ports.MobiusResidueRealisation.mobiusLiveResidue_defined
#print axioms LeanCompCert.Ports.MobiusResidueScalar.residue_denote
#print axioms LeanCompCert.Ports.MobiusResidueScalar.residue_defined
#print axioms LeanCompCert.Ports.MobiusResidueTrial.signal_read
#print axioms LeanCompCert.Ports.MobiusResidueTrial.fullBody_denote
#print axioms LeanCompCert.Ports.MobiusResidueTrial.fullStep_fullObs
#print axioms LeanCompCert.Ports.MobiusResidueTrial.safeRun_append
#print axioms LeanCompCert.Ports.MobiusResidueTrial.safeCheck_eq_true
#print axioms LeanCompCert.Ports.MobiusResidueTrial.fullProgram_denote
#print axioms LeanCompCert.Ports.MobiusResidueTrial.roundSig_last
#print axioms LeanCompCert.Ports.MobiusResidueTrial.fullBlock_spec
#print axioms LeanCompCert.Ports.MobiusResidueTrial.fullValue_eq_trialResAt
#print axioms LeanCompCert.Ports.MobiusExtremaScalar.residue_denote
#print axioms LeanCompCert.Ports.MobiusExtremaTrial.fullProgram_denote
#print axioms LeanCompCert.Ports.MobiusExtremaTrialWindow.finalAbs_eq_trialExtAt
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.readSig_arun_signalBlock
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.readSig_eq_muSig_of_cell
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.signalBlock_defined
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.denote_signalBlock_readSig
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.readSig_arun_postSignal
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.readSig_arun_coreBody
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.selectorBlock_main
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.selectorBlock_main_markGate
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.signalInput_main_controls
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.markBeforeProd_main_addresses
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.arun_markPrefix_main_cells
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.signalInput_main_cells
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.readSig_arun_coreBody_main
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.readSig_arun_coreBody_eq_muSig
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.readSig_arun_coreBody_eq_muSig_of_input_cell
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.selectorBlock_markGate
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.markBeforeProd_live_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.markBetweenStores_live
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markPrefix_live_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.signalInput_mark_live_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postBeforeClear_mark_addresses
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postRootGate_mark
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postRootAddress_mark
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_postSignal_mark_cells
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.signalBlock_mark_controls
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_coreBody_mark_live_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markSetup_start
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.roundBeforeProd_live
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markRound_live
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markPrefix_live_start
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.signalInput_mark_live_start
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_coreBody_mark_live_start
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorGate_marked
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorGate_exhausted
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorIndex_hold
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorIndex_advance
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorLoad_table
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorPrime_hold
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorPrime_advance
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorOffset_first
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorFinish_hold
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorFinish_advance
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorFinish_terminal
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.roundAfterFlag_hold
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.roundAfterFlag_advance
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.roundCursorInput_live
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.roundCursorInput_exhausted
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.roundBeforeProd_exhausted_addresses
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.roundCursorInput_exhausted_cell
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markRound_exhausted_cell
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markRound_cursor_live
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markRound_cursor_advance
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markSetup_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markPrefix_cursor_live_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markPrefix_cursor_advance_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markPrefix_exhausted_cell_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markPrefix_cursor_live_start
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.selectorBlock_limit_main
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.selectorBlock_limit_root
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.signalInput_cursor_live_nonstart_of_limit
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.signalInput_exhausted_cell_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.signalInput_cursor_advance_nonstart_of_limit
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.signalInput_cursor_live_start_of_limit
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postAfterRootStore_nowrap
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postAfterRootStore_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postAfterRootStore_rootTransition
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postBeforeClear_acc_addresses
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_postSignal_acc_clears
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postRootGate_collect
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postRootGate_marked
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postRootAddress_collect
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postBeforeRootStore_collect_address
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postAfterRootStore_write_collect
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postAfterRootStore_write_disabled
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_rootWriteSuffix_collect
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_rootWriteSuffix_collect_frame
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_rootWriteSuffix_marked_preserves
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeInvariant.isPrime_of_unmarked_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeInvariant.unmarked_of_prime_lt
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeInvariant.unmarked_of_prime
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeInvariant.unmarked_iff_prime
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTable.empty
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTable.append_next
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTable.retain_next
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTable.unmarked_iff_prime_next
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTable.append_next_of_unmarked
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTable.retain_next_of_marked
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.TablePrefix.append_single
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.TablePrefix.frame_below
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.MachineTableRep.guard_pos
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.rootWriteSuffix_append
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.rootWriteSuffix_retain
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.TablePrefix.frame_cells
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.TablePrefix.cell_property
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.TablePrefix.cell_eq
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.TablePrefix.of_append_left
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.MachineTableRep.cell_prime
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.MachineTableRep.cell_bounds
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.MachineTableRep.same_main_cell
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.RootTableInv.append_next
#print axioms LeanCompCert.Ports.ArraySegMobiusPrimeTableRep.RootTableInv.retain_next
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootCellStep_hit
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootCellStep_miss
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootCellFoldFrom_append
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.unmarkedBool_eq_true_iff
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.unmarkedBool_iff_prime_next
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootTableStep_preserves
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootCellFold_eq_zero_of_unmarked
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootCellFold_single_hit_ne_zero
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.flagUpdate_encodeRootLogic
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootCellFold_flag_eq_encode
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootLogicFold_square_iff
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootLogicFold_parity_eq
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.encodedProduct_decode
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.isPrime_coprime_of_ne
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.prime_coprime_divisorProduct
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.divisorProduct_dvd
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.divisorProduct_lt_modulus
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.dvd_divisorProduct_of_mem_dvd
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.divisorProduct_eq_one_iff_unmarked
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.divisorProduct_pos
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootCellFoldFrom_prod_eq
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootCellFold_prod_eq_encoded
#print axioms LeanCompCert.Ports.ArraySegMobiusRootCellFold.rootCellFold_prod_eq_zero_iff_unmarked
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.firstOffset_dvd
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.dvd_window_advance
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_mark_tableCell
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_mark_tableCell_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_mark_tableCell_start
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_mark_live_nonstart_frame
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_mark_live_nonstart_machineCell
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_mark_exhausted_machineCell
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_cursor_live_nonstart_of_limit
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.cursorIndex_advance_terminal
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.roundAfterFlag_advance_terminal
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markRound_cursor_terminal
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_markPrefix_cursor_terminal_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.signalInput_cursor_terminal_nonstart_of_limit
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_cursor_live_start_of_limit
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_cursor_advance_nonstart_of_limit
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_cursor_terminal_nonstart_of_limit
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_cursor_terminal_main_of_tableRep
#print axioms LeanCompCert.Ports.ArraySegMobiusRootSchedule.arun_coreBody_mark_live_start_machineCell
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.cursorStep_live
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.cursorStep_advance
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.cursorStep_terminal
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.scheduleStep_exhausted
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.cursorStep_table_congr
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.scheduleStep_table_congr
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.cursorStep_main_ready
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.scheduleStart_cursor_ready
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.scheduleStep_cursor_main_ready
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.scheduleRun_cursor_main_ready
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_simulates_scheduleRun
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_mark_position
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_mark_position_from
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_succ_start
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.arun_coreBody_mark_preserves_tableRep
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_mark_tableCell
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_mark_preserves_tableRep
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.arun_coreBody_simulates_live_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.arun_coreBody_simulates_advance_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.arun_coreBody_simulates_advance_nonstart_of_tableRep
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.arun_coreBody_simulates_advance_main_of_tableRep
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.arun_coreBody_simulates_terminal_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.arun_coreBody_mark_preserves_tableRep_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_mark_preserves_tableRep_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.arun_coreBody_mark_preserves_tableRep_start
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.MainNonstartReady.of_cursor
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.arun_coreBody_simulates_main_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_simulates_main_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_simulates_main_nonstart_of_cursor
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_simulates_main_nonstart_from
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_mark_preserves_tableRep_nonstart_from
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.arun_coreBody_simulates_start
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_simulates_main_from_start
#print axioms LeanCompCert.Ports.ArraySegMobiusCursorModel.bodyRun_mark_preserves_tableRep_from_start
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.primeCellScan_eq_rootCellStep
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.referenceCellSchedule_eq_rootCellFoldFrom
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.referenceCellSchedule_eq_rootCellFold
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.tracedScheduleRun_state
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.tracedScheduleRun_cell
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.scheduleRun_cell_eq_eventCellFold
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.eventCellFold_referenceLiveEvents
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.scheduleRun_cell_eq_rootCellFoldFrom_of_trace
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.tracedScheduleRun_live_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.tracedScheduleRun_live_block
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.tracedScheduleRun_add
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.tracedScheduleRun_prime_phase
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.tracedScheduleRun_terminal_phase
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.tracedScheduleRun_prime_list
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.tracedScheduleRun_one_raw_start
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.fullMainEventTrace_exact
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.tracedScheduleRun_terminal_slack
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.fullMainEventTrace_of_budget
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.liveCount_add_one_le_budget
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.cursorScheduleFuel_le_primeBudget
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.firstOffset_eq_mod_of_dvd
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.firstOffset_add_div_eq_of_dvd
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.eventCellFold_progression
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.mem_cursor_progression_iff
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.eventCellFold_cursorLiveEvents
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.eventCellFold_cursorReferenceLiveEvents
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.cursorTable_of_tablePrefix
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.scheduleRun_from_start_cell_eq_rootCellFoldFrom_of_budget
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.machineCell_eq_rootCellFoldFrom_of_main_schedule
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.bodyRun_main_cell_eq_rootCellFoldFrom
#print axioms LeanCompCert.Ports.ArraySegMobiusScheduleFold.bodyRun_main_cell_eq_rootCellFold
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.LimitTableRep.cell_prime_bounds
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.LimitTableRep.same_cell
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.LimitNonstartReady.of_cursor
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.LimitNonstartReady.toMain
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.arun_coreBody_mark_preserves_limitTableRep_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.arun_coreBody_mark_preserves_limitTableRep_start
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.arun_coreBody_simulates_terminal_limit
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.arun_coreBody_simulates_limit_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.bodyRun_simulates_limit_nonstart_of_cursor
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.bodyRun_simulates_limit_from_start
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.bodyRun_simulates_root_from_start
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.machineCell_eq_rootCellFoldFrom_of_limit_schedule
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.bodyRun_root_cell_eq_rootCellFoldFrom
#print axioms LeanCompCert.Ports.ArraySegMobiusRootMarkFold.bodyRun_root_cell_eq_rootCellFold
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRun.indexedBodyRun_succ_start
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRun.indexedBodyRun_add
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRun.indexedBodyRun_rZero
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRun.indexedBodyRun_mark_position
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRun.indexedBodyRun_mark_preserves_tableRep_nonstart
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRun.indexedBodyRun_simulates_limit_nonstart_of_cursor
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRun.indexedBodyRun_simulates_root_from_start
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRun.indexedBodyRun_root_mark_preserves_full_table
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRun.indexedBodyRun_root_cell_eq_rootCellFoldFrom
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRun.indexedBodyRun_root_cell_eq_rootCellFold
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootPrefix.indexedBodyRun_first_root_acc_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootPrefix.indexedBodyRun_first_root_acc_complete_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootPrefix.indexedBodyRun_first_root_acc_complete_transition
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootPrefix.indexedBodyRun_later_root_acc_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootPrefix.indexedBodyRun_later_root_acc_complete_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootPrefix.indexedBodyRun_later_root_acc_complete_transition
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.TablePrefix.append_cons_boundary
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.BootstrapTableView.of_rootTable_append_cons
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.rootTableStep_has_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.bootstrapExtendedBool_eq_true_iff
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.rootScanTable_has_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.BootstrapTableView.of_rootTable_extension
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.BootstrapTableView.of_first_root_scan
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.BootstrapTableView.frame_of_gate_disabled
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.BootstrapTableView.next_rootTableStep
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.BootstrapTableView.one_retain
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.BootstrapTableView.bootstrap_retain
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.indexedBodyRun_first_root_bootstrap_view
#print axioms LeanCompCert.Ports.ArraySegMobiusRootBootstrapInv.indexedBodyRun_later_root_bootstrap_view
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootMixed.rootScanMixed_zero
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootMixed.rootScanMixed_succ
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootMixed.rootScanMixed_eq_boot_of_le
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootMixed.rootScanMixed_has_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootMixed.indexedBodyRun_mixed_root_acc_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootMixed.indexedBodyRun_mixed_root_acc_complete_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootMixed.indexedBodyRun_mixed_root_acc_complete_bootstrap_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootWindows.indexedRootWindow_bootstrap_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootWindows.indexedRootWindow_mixed_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootWindows.indexedRootWindow_later_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootWindows.indexedRootWindow_later_transition
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedBodyRun_main_acc_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedBodyRun_main_acc_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedBodyRun_main_acc_tableCell
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedBodyRun_main_acc_preserves_tableRep
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedBodyRun_simulates_main_from_start
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedBodyRun_main_cell_eq_rootCellFoldFrom
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedBodyRun_main_cell_eq_rootCellFold
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedBodyRun_main_mark_preserves_tableRep
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedBodyRun_main_window_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedWindowRun_zero
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedWindowRun_succ
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedWindowRun_add
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedWindowRun_main_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedMain.indexedRootOutput_then_main_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootOuter.rootLaterWindows_zero
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootOuter.rootLaterWindows_succ
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootOuter.indexedWindowRun_bootstrap_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootOuter.indexedBootstrapWindows_mixed_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootOuter.indexedWindowRun_later_root_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootOuter.indexedLaterWindows_final_transition
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedRootOuter.indexedLaterWindows_then_main_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedProgram.coreEntry_rootTableInv
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedProgram.coreEntry_bootstrap_view
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedProgram.coreEntry_root_position
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedProgram.coreEntry_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedFull.indexedProductionCore_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusResidueFrame.arun_coreBody_congr
#print axioms LeanCompCert.Ports.ArraySegMobiusResidueFrame.arun_residue_core_frame
#print axioms LeanCompCert.Ports.ArraySegMobiusResidueFrame.combinedRun_core
#print axioms LeanCompCert.Ports.ArraySegMobiusResidueFrame.combinedProductionCore_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusResidueFold.readRes_arun_residue
#print axioms LeanCompCert.Ports.ArraySegMobiusResidueFold.readRes_combinedIndexedRun_eq_resFold
#print axioms LeanCompCert.Ports.ArraySegMobiusResidueFold.combinedIndexedRun_add
#print axioms LeanCompCert.Ports.ArraySegMobiusResidueFold.combinedWindowRun_add
#print axioms LeanCompCert.Ports.ArraySegMobiusResidueFold.readRes_arun_combined_mark
#print axioms LeanCompCert.Ports.ArraySegMobiusResidueFold.readRes_arun_combined_root_acc
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.combinedIndexedRun_core
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.combinedWindowRun_core
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.readRes_combinedWindowRun_inv_of_step
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.combinedIndexedRun_mark_event_divisors_ready
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.readRes_combinedIndexedRun_mark_prefix_eq
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.combinedIndexedRun_root_acc_event_divisors_ready
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.readRes_combinedIndexedRun_root_acc_prefix_eq
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.readSig_indexedBodyRun_main_acc_eq_rootFoldValue
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.readSig_combinedIndexedRun_main_acc_eq_rootFoldValue
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.readSig_indexed_main_window_cell_eq_rootFoldValue
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.readSig_indexedWindowRun_main_cell_eq_rootFoldValue
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.readSig_combinedIndexedWindowRun_main_cell_eq_rootFoldValue
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.combined_main_event_divisors_ready
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.readRes_combinedIndexedRun_main_acc_prefix_inv
#print axioms LeanCompCert.Ports.ArraySegMobiusIndexedSignal.readRes_combinedIndexedRun_main_window_inv
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.readSig_arun_signalBlock_gated
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.readSig_arun_coreBody_gated
#print axioms LeanCompCert.Ports.ArraySegMobiusIdleSignal.readSig_arun_coreBody_mark_idle
#print axioms LeanCompCert.Ports.ArraySegMobiusIdleSignal.readSig_arun_coreBody_root_acc_idle
#print axioms LeanCompCert.Ports.ArraySegMobiusIdleSignal.resStep_readSig_arun_coreBody_mark
#print axioms LeanCompCert.Ports.ArraySegMobiusIdleSignal.resStep_readSig_arun_coreBody_root_acc
#print axioms LeanCompCert.Ports.ArraySegMobiusIdleSignal.mark_event_divisors_ready
#print axioms LeanCompCert.Ports.ArraySegMobiusIdleSignal.root_acc_event_divisors_ready
#print axioms LeanCompCert.Ports.ArraySegMobiusCellRep.decodeCell_bits
#print axioms LeanCompCert.Ports.ArraySegMobiusCellRep.rootFoldValue_eq_or
#print axioms LeanCompCert.Ports.ArraySegMobiusCellRep.decodeCell_eq_muSig_decodedValue
#print axioms LeanCompCert.Ports.ArraySegMobiusCellRep.rootCellFold_cellRepresents
#print axioms LeanCompCert.Ports.ArraySegMobiusCellRep.cellRepresents_of_cell_eq_rootCellFold
#print axioms LeanCompCert.Ports.ArraySegMobiusCellRep.rootFoldValue_eq_finiteRootValue
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.arun_coreBody_main_acc_nowrap
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.arun_coreBody_main_acc_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.bodyRun_main_acc_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.bodyRun_main_acc_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.bodyRun_main_acc_current_cellRepresents
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.readSig_bodyRun_main_acc_eq_rootFoldValue
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.readSig_compiled_main_window_cell_eq_rootFoldValue
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.arun_markPrefix_main_frame
#print axioms LeanCompCert.Ports.ArraySegMobiusSignal.signalInput_main_frame
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.arun_coreBody_main_acc_tableCell
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.bodyRun_main_acc_tableCell
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.bodyRun_main_acc_preserves_tableRep
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.bodyRun_add
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.bodyRun_main_window_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.windowRun_main_complete
#print axioms LeanCompCert.Ports.ArraySegMobiusAccumulation.readSig_windowRun_main_cell_eq_rootFoldValue
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.postRootGate_one
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.selectorBlock_root_acc_controls
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.signalInput_root_acc_controls
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.signalBlock_root_candidate
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.signalBlock_root_acc_controls
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_eq_rootStoreInput
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_eq_rootCursorInput
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootStoreInput_tableCell
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootStoreInput_frame
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootStoreInput_clears
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootStoreInput_reg_frame
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootStoreInput_controls
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootCursorInput_controls
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootCursorInput_one_controls
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_one_nowrap
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_nowrap
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_transition
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootStoreInput_rootTableInv
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootWriteSuffix_next_eq_rootTableStep
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootWriteSuffix_frame_of_rootTableStep
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootWriteSuffix_disabled_preserves
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.rootWriteSuffix_retain_of_gate_disabled
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_frame_of_gate_disabled
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_frame_of_rootTableStep
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.unmarkedBool_boot_eq_current_next
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.not_unmarked_of_primeTableInv_le
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_one_retain
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_bootstrap_retain
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_bootstrap_table_cells
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_bootstrap_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_next_table_cells
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_next_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_next_transition
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.arun_coreBody_root_acc_next_eq_rootTableStep
#print axioms LeanCompCert.Ports.ArraySegMobiusRootAccumulation.signalBlock_root_candidate_unmarked
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.rootScanTable_zero
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.rootScanTable_succ
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.rootScanTable_eq_boot_of_le
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.bodyRun_first_root_acc_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.bodyRun_first_root_acc_complete_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.rootScanFrom_zero
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.rootScanFrom_succ
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.rootScanFrom_has_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.bodyRun_later_root_acc_prefix
#print axioms LeanCompCert.Ports.ArraySegMobiusRootPrefix.bodyRun_later_root_acc_complete_wrap
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.postBeforeRootStore_mark_collect
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_postSignal_mark_frame
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_postSignal_mark_nowrap
#print axioms LeanCompCert.Ports.ArraySegMobiusMark.arun_coreBody_mark_nowrap
#print axioms LeanCompCert.Ports.ArraySegSieve.mobiusLiveInit_all
#print axioms LeanCompCert.Ports.ArraySegSieve.mobiusLiveEpilogue_all
#print axioms LeanCompCert.Ports.ArraySegSieve.mobiusLiveProgram_wf
#print axioms LeanCompCert.Ports.ArraySegSieve.mobiusLiveProgram_compiled
#print axioms LeanCompCert.Testing.ArraySegCertificate.program_wf
#print axioms LeanCompCert.Verified.LogFixed.sq62_eq
#print axioms LeanCompCert.Verified.LogFixed.logIter_spec
#print axioms LeanCompCert.Verified.LogFixed.logFix_bracket
#print axioms LeanCompCert.Verified.LogFixed.logFold_bracket
#print axioms LeanCompCert.Verified.LogFixed.errB_le_48
#print axioms LeanCompCert.Ports.LogFixPort.logRoundProgram_wf
#print axioms LeanCompCert.Ports.LogFixPort.logRoundProgram_compiled

-- The two-limb accumulator, and the psi residue it makes possible
#print axioms LeanCompCert.Verified.AddWide.carry_bit
#print axioms LeanCompCert.Verified.AddWide.borrow_bit
#print axioms LeanCompCert.Verified.AddWide.addWide_spec
#print axioms LeanCompCert.Verified.AddWide.addWide_exact
#print axioms LeanCompCert.Verified.AddWide.subWide_exact
#print axioms LeanCompCert.Verified.AddWide.sumWideFrom_spec
#print axioms LeanCompCert.Verified.AddWide.sumWide_spec
#print axioms LeanCompCert.Verified.LogAccum.logFix_lt
#print axioms LeanCompCert.Verified.LogAccum.logFold_le
#print axioms LeanCompCert.Verified.LogAccum.logFoldWide
#print axioms LeanCompCert.Verified.LogAccum.logFoldWide_bracket
#print axioms LeanCompCert.Ports.AddWidePort.addWideBody_denote
#print axioms LeanCompCert.Ports.AddWidePort.addWideLoBody_denote
#print axioms LeanCompCert.Ports.AddWidePort.subWideLoBody_denote
#print axioms LeanCompCert.Ports.AddWidePort.accProgram_wf
#print axioms LeanCompCert.Ports.AddWidePort.accProgram_compiled
#print axioms LeanCompCert.Ports.PsiSegSieve.body_all
#print axioms LeanCompCert.Ports.PsiSegSieve.init_all
#print axioms LeanCompCert.Ports.PsiSegSieve.epilogue_all
#print axioms LeanCompCert.Ports.PsiSegSieve.psiProgram_wf
#print axioms LeanCompCert.Ports.PsiSegSieve.psiProgram_compiled

-- Interval bisection in dyadic fixed point, and the Helfgott A.36 low branch
#print axioms LeanCompCert.Verified.DyadicBisect.chain_cover
#print axioms LeanCompCert.Verified.DyadicBisect.sqrtI_encloses
#print axioms LeanCompCert.Verified.DyadicBisect.sqrtOK_encloses
#print axioms LeanCompCert.Verified.DyadicBisect.sqrtOK_wf
#print axioms LeanCompCert.Verified.DyadicBisect.allBelow_iff
#print axioms LeanCompCert.Verified.DyadicBisect.sweepFold_eq_zero_iff
#print axioms LeanCompCert.Verified.DyadicBisect.Grid.chain
#print axioms LeanCompCert.Verified.DyadicBisect.Grid.cell_wf
#print axioms LeanCompCert.Verified.DyadicBisect.Grid.loM_mul_le
#print axioms LeanCompCert.Verified.DyadicBisect.Grid.le_hiM_mul
#print axioms LeanCompCert.Ports.A36Bisect.sweep_ok
#print axioms LeanCompCert.Ports.A36Bisect.leaf_passes
#print axioms LeanCompCert.Ports.A36Bisect.leaf_sound
#print axioms LeanCompCert.Ports.A36Bisect.leafOKAt_sound
#print axioms LeanCompCert.Ports.A36Bisect.j_encloses
#print axioms LeanCompCert.Ports.A36Bisect.v_encloses
#print axioms LeanCompCert.Ports.A36Bisect.w_encloses
#print axioms LeanCompCert.Ports.A36Bisect.cells_chain
#print axioms LeanCompCert.Ports.A36Bisect.cells_wf
#print axioms LeanCompCert.Ports.A36Bisect.cells_cover
#print axioms LeanCompCert.Ports.A36BisectProgram.body_wf
#print axioms LeanCompCert.Ports.A36BisectProgram.init_wf
#print axioms LeanCompCert.Ports.A36BisectProgram.programAt_wf
#print axioms LeanCompCert.Ports.A36BisectProgram.program_wf
#print axioms LeanCompCert.Ports.A36BisectProgram.agree_pass
#print axioms LeanCompCert.Ports.A36BisectProgram.sweep_pass
#print axioms LeanCompCert.Ports.A36BisectProgram.agree_fail
#print axioms LeanCompCert.Ports.A36BisectProgram.sweep_fail
#print axioms LeanCompCert.Ports.A36Bisect.differences_exact
#print axioms LeanCompCert.Ports.A36Bisect.den_pos
-- The segmented factorisation sieve, and the R2* residue
#print axioms LeanCompCert.Ports.R2SegSieve.storeLit_all
#print axioms LeanCompCert.Ports.R2SegSieve.storeResult_all
#print axioms LeanCompCert.Ports.R2SegSieve.storeLits_all
#print axioms LeanCompCert.Ports.R2SegSieve.seedRegs_all
#print axioms LeanCompCert.Ports.R2SegSieve.seedList_ok
#print axioms LeanCompCert.Ports.R2SegSieve.body_all
#print axioms LeanCompCert.Ports.R2SegSieve.init_all
#print axioms LeanCompCert.Ports.R2SegSieve.epilogue_all
#print axioms LeanCompCert.Ports.R2SegSieve.r2Program_wf
#print axioms LeanCompCert.Ports.R2SegSieve.r2Program_compiled

-- The CDEM Abel increment scan, and its certificate
#print axioms LeanCompCert.Ports.CDEMAbelScan.storeLit_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.storeLits_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.seedRegs_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.seedList_ok
#print axioms LeanCompCert.Ports.CDEMAbelScan.storeResult_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.selectors_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.sieveBody_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.markBody_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.accHead_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.accProd_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.accBisect_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.tailBody_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.body_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.init_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.epilogue_all
#print axioms LeanCompCert.Ports.CDEMAbelScan.abelProgram_wf
#print axioms LeanCompCert.Ports.CDEMAbelScan.abelProgram_compiled
#print axioms LeanCompCert.Testing.AbelScanCertificate.program_wf
#print axioms LeanCompCert.Verified.ExpFixed.bit_split
#print axioms LeanCompCert.Verified.ExpFixed.expIter_range
#print axioms LeanCompCert.Verified.ExpFixed.expIter_spec
#print axioms LeanCompCert.Verified.ExpFixed.expFix_bracket
#print axioms LeanCompCert.Verified.ExpFixed.expFix_rel_width
#print axioms LeanCompCert.Verified.ExpFixed.expIter_fits_64
#print axioms LeanCompCert.Verified.ExpFixed.expOK_sound
#print axioms LeanCompCert.Verified.ExpFixed.rpow_bracket
#print axioms LeanCompCert.Ports.ExpFixPort.rootDigits_length
#print axioms LeanCompCert.Ports.ExpFixPort.roundBody_length
#print axioms LeanCompCert.Ports.ExpFixPort.expCfg_fits
#print axioms LeanCompCert.Ports.ExpFixPort.expProgram_wf
#print axioms LeanCompCert.Ports.ExpFixPort.expProgram_compiled

-- Dirichlet L zero-ladder checker: the Platt Theorem 7.1 finite content
#print axioms LeanCompCert.Ports.DirichletLadder.ladderProgram_wf
#print axioms LeanCompCert.Ports.DirichletLadder.ladderProgram_compiled
#print axioms LeanCompCert.Ports.DirichletLadder.bodyBlock_wf
#print axioms LeanCompCert.Ports.DirichletLadder.initBlock_wf
#print axioms LeanCompCert.Ports.DirichletLadder.epilogueBlock_wf
#print axioms LeanCompCert.Ports.DirichletLadder.ainstrWFB_correct
#print axioms LeanCompCert.Testing.DirichletLadderCertificate.program_wf
#print axioms LeanCompCert.Verified.Prop1224Margin.le_cdiv_mul
#print axioms LeanCompCert.Verified.Prop1224Margin.k0_covers
#print axioms LeanCompCert.Verified.Prop1224Margin.lamCube_ge
#print axioms LeanCompCert.Verified.Prop1224Margin.lamHi_covers
#print axioms LeanCompCert.Verified.Prop1224Margin.marginOK_sound
#print axioms LeanCompCert.Verified.Prop1224Margin.gqTerm_ge
#print axioms LeanCompCert.Verified.Prop1224Margin.gqTerm_lt
#print axioms LeanCompCert.Verified.Prop1224Margin.cbrtOK_sound
#print axioms LeanCompCert.Verified.Prop1224Margin.cbrtOK_mono
#print axioms LeanCompCert.Verified.Prop1224Margin.envHi_ge
#print axioms LeanCompCert.Verified.Prop1224Margin.phiLo_le
#print axioms LeanCompCert.Verified.Prop1224Margin.posLo_le
#print axioms LeanCompCert.Ports.Prop1224Cell.cbrtStep_all
#print axioms LeanCompCert.Ports.Prop1224Cell.coprimeBody_all
#print axioms LeanCompCert.Ports.Prop1224Cell.body_all
#print axioms LeanCompCert.Ports.Prop1224Cell.init_all
#print axioms LeanCompCert.Ports.Prop1224Cell.epilogue_all
#print axioms LeanCompCert.Ports.Prop1224Cell.cellProgram_wf
#print axioms LeanCompCert.Ports.Prop1224Cell.cellProgram_compiled
#print axioms LeanCompCert.Ports.Prop1224Row.logRound_all
#print axioms LeanCompCert.Ports.Prop1224Row.expRound_all
#print axioms LeanCompCert.Ports.Prop1224Row.logEngine_all
#print axioms LeanCompCert.Ports.Prop1224Row.expEngine_all
#print axioms LeanCompCert.Ports.Prop1224Row.markBody_all
#print axioms LeanCompCert.Ports.Prop1224Row.deriveBody_all
#print axioms LeanCompCert.Ports.Prop1224Row.latchBody_all
#print axioms LeanCompCert.Ports.Prop1224Row.finishBody_all
#print axioms LeanCompCert.Ports.Prop1224Row.tailBody_all
#print axioms LeanCompCert.Ports.Prop1224Row.body_all
#print axioms LeanCompCert.Ports.Prop1224Row.init_all
#print axioms LeanCompCert.Ports.Prop1224Row.epilogue_all
#print axioms LeanCompCert.Ports.Prop1224Row.rowProgram_wf
#print axioms LeanCompCert.Ports.Prop1224Row.rowProgram_compiled

-- The Ramaré m-star array machine.  These are the two top-level simulation
-- statements used by the external-run certificate: one exposes the exact
-- candidate-level reference value, and the other packages that equality as
-- an `AProgramRefinement`.  Neither evaluates the production fold.
#print axioms LeanCompCert.Ports.RamareMStar140M.msProgram_denote
#print axioms LeanCompCert.Ports.RamareMStar140M.msEncoding

-- The run-receipt standard (`LeanCompCert/Attest/`).  It is in the axiom-free
-- library on purpose: `RunAdmission` is a HYPOTHESIS here, discharged only by
-- a consumer who opts into a named axiom.  If any of these ever acquires an
-- axiom, the composition has stopped being conditional and the gate fails.
#print axioms LeanCompCert.Attest.receiptBinds_sound
#print axioms LeanCompCert.Attest.receiptBinds_programHash
#print axioms LeanCompCert.Attest.receiptBinds_false_of_noEmission
#print axioms LeanCompCert.Attest.receiptBinds_false_of_programHash_ne
#print axioms LeanCompCert.Attest.receiptBinds_false_of_paramsHash_ne
#print axioms LeanCompCert.Attest.receiptBinds_false_of_value_ne
#print axioms LeanCompCert.Attest.receiptBinds_false_of_verdict_ne
#print axioms LeanCompCert.Attest.receiptBinds_false_of_nonce_ne
#print axioms LeanCompCert.Attest.receiptBinds_false_of_badSignature
#print axioms LeanCompCert.Attest.receiptBinds_false_of_kind_ne
#print axioms LeanCompCert.Attest.receiptBinds_false_of_route_ne
#print axioms LeanCompCert.Attest.receiptBinds_false_of_digestName_ne
#print axioms LeanCompCert.Attest.receiptBindsProved_sound
#print axioms LeanCompCert.Attest.emitFor_rolled
#print axioms LeanCompCert.Attest.ArtifactBody.modelResult_eq_sourceResult
#print axioms LeanCompCert.Attest.ArtifactBody.rolled_Returns_iff_denote
#print axioms LeanCompCert.Attest.modelResult_of_receipt
#print axioms LeanCompCert.Attest.returns_of_receipt
#print axioms LeanCompCert.Attest.returns_of_receipt_proved
#print axioms LeanCompCert.Attest.decide_of_receipt
#print axioms LeanCompCert.Attest.not_selfTested_of_alwaysTrue
#print axioms LeanCompCert.Attest.not_selfTested_of_alwaysFalse
#print axioms LeanCompCert.Attest.not_selfTested_of_messageIgnoring
#print axioms LeanCompCert.Attest.not_selfTested_of_constantDigest

-- M9: the receipt join, now checked by the kernel rather than admitted.  These
-- are the goals that used to be one named axiom per artifact; if any of them
-- ever needs `ofReduceBool` or a bespoke axiom, this gate says so.
#print axioms LeanCompCertTests.Attest.compiles_in_kernel
#print axioms LeanCompCertTests.Attest.source_in_kernel
#print axioms LeanCompCertTests.Attest.binds_programHash

-- The program ledger (`LeanCompCert/Attest/Ledger.lean`).  Also axiom-free, and
-- for the same reason: it RECORDS runs, it never lets one become a theorem.
-- `ChainProof.prop_of_receipt` is what makes the ledger's `chain proved` column
-- more than a label — it is the composition a `.chained` entry licenses, and it
-- still takes `RunAdmission` as a hypothesis.
#print axioms LeanCompCert.Attest.ChainProof.prop_of_receipt
#print axioms LeanCompCert.Attest.ChainProof.prop_of_receipt_proved

-- The one registered program with `Algorithm.Ensures` AND `ProgramRefinement`
-- above it, and therefore the one whose `chain proved` column is `true` on the
-- strongest evidence in the package.  `program_denote` is proved structurally
-- for every input; the loop is never evaluated.
#print axioms LeanCompCert.Testing.AlgorithmProof.sumRangeMod_eq_foldl
#print axioms LeanCompCert.Testing.AlgorithmProof.reference_sound
#print axioms LeanCompCert.Testing.AlgorithmProof.program_denote
#print axioms LeanCompCert.Testing.AlgorithmProof.example_program_accepts
#print axioms LeanCompCert.Testing.AlgorithmProof.example_result
-- The rolled route, now inside the proved C model.  The `while` rule is
-- fuelled and covers exactly the counted shape `emitRolled` produces; these
-- are the theorems that say so, and the acceptance that a rolled artifact
-- passes the STRICT `receiptBindsProved`.
#print axioms LeanCompCert.Proof.evalCWhile_unroll
#print axioms LeanCompCert.Proof.evalCStmtFuel_of_loopFree
#print axioms LeanCompCert.Proof.evalCSequenceFuel_of_loopFree
#print axioms LeanCompCert.Proof.lowerSequence_loopFree
#print axioms LeanCompCert.Verified.Reflect.evalCWhile_rolled
#print axioms LeanCompCert.Verified.Reflect.rolledResult_eq_denote
#print axioms LeanCompCert.Verified.Reflect.counterAugment_sourceResult
#print axioms LeanCompCertTests.Attest.Rolled.rolled_covered
#print axioms LeanCompCertTests.Attest.Rolled.rolled_proved_is_binds
#print axioms LeanCompCertTests.Attest.Rolled.rolled_model_preserved
#print axioms LeanCompCertTests.Attest.Rolled.rolled_source_in_kernel
#print axioms LeanCompCertTests.Attest.Rolled.denote_of_admitted_rolled_receipt
