#!/usr/bin/env python3
"""Bind a clightgen-produced array function to ClightMemorySem.

The input .v file is copied verbatim and compiled by Coq.  The generated check
kernel-computes that the exact production function body is inside the supported
rolled/memory fragment, then specializes the generic statement and function
soundness theorems to that exact AST.
"""

import argparse
import shutil
import subprocess
import sys
from pathlib import Path


DEFAULT_COMPCERT = "/home/gersh/CompCert-3.17"
DEFAULT_COQC = "/home/gersh/.opam/4.14.2/bin/coqc"


CHECK = r'''(* Generated by clight-array-verify.py -- do not edit. *)
From compcert Require Import Coqlib Maps Integers Values Events Memory.
From compcert Require Import Globalenvs.
From compcert Require Import AST Ctypes Cop Clight ClightBigstep Clightdefs.
Require Import Direct.ArrayCert Direct.ClightMemorySem Direct.ClightFlatSem.

Definition production_f : function := {function}.

Lemma production_body_supported :
  mem_stmt_supported (fn_body production_f) = true.
Proof. vm_compute. reflexivity. Qed.

Lemma production_flat_body_supported :
  flat_stmt_supported (fn_body production_f) = true.
Proof. vm_compute. reflexivity. Qed.

(** Extract the exact straight-line work portion of the generated loop.  The
    count and per-atom support proof prevent the fast step certificate from
    silently drifting away from the production AST. *)
Definition production_loop_parts :=
  Eval vm_compute in split_first_loop (fn_body production_f).
Definition production_loop_head : statement :=
  match production_loop_parts with
  | Some (_, head, _, _) => head
  | None => Sskip
  end.
Definition production_loop_work : statement :=
  match production_loop_head with
  | Ssequence _ work => work
  | _ => Sskip
  end.
Definition production_loop_atoms : list statement :=
  Eval vm_compute in flatten_sequence production_loop_work.

Lemma production_loop_atom_count :
  List.length production_loop_atoms = 68%nat.
Proof. vm_compute. reflexivity. Qed.

Lemma production_loop_atoms_supported :
  Forall (fun s => flat_stmt_supported s = true) production_loop_atoms.
Proof. vm_compute. repeat constructor. Qed.

Theorem production_flat_run_simulates_compcert :
  forall fuel array_block limit flat m flat' out,
  flat_block_rel flat.(flat_array) m array_block limit ->
  run_flat_fuel fuel (genv_cenv (globalenv prog)) array_block
    limit (fn_body production_f) flat = Some (flat', out) ->
  exists m',
    run_mem_fuel fuel (genv_cenv (globalenv prog)) m
      (fn_body production_f) flat.(flat_temps) =
        Some (flat'.(flat_temps), (m', out)) /\
    flat_block_rel flat'.(flat_array) m' array_block limit.
Proof.
  intros fuel array_block limit flat m flat' out REL RUN.
  eapply run_flat_fuel_sim.
  - exact production_flat_body_supported.
  - exact REL.
  - exact RUN.
Qed.

Lemma production_params_norepet :
  list_norepet (var_names (fn_params production_f)).
Proof. vm_compute. constructor; [tauto | constructor]. Qed.

Lemma production_params_temps_disjoint :
  list_disjoint (var_names (fn_params production_f))
    (var_names (fn_temps production_f)).
Proof.
  red. vm_compute. intros x y HX HY HXY.
  repeat match goal with
  | h : _ \/ _ |- _ => destruct h as [h|h]
  end; subst; congruence.
Qed.

Lemma production_vars_nil : fn_vars production_f = nil.
Proof. vm_compute. reflexivity. Qed.

(** Exact-AST statement endpoint. *)
Theorem production_body_bigstep :
  forall fuel fe ge en m le le' m' out,
  run_mem_fuel fuel (genv_cenv ge) m (fn_body production_f) le =
    Some (le', (m', out)) ->
  ClightBigstep.exec_stmt fe ge en le m (fn_body production_f)
    E0 le' m' out.
Proof. intros fuel fe ge en m le le' m' out RUN.
  eapply run_mem_fuel_sound. exact RUN.
Qed.

(** Exact-AST Clight2 function endpoint. *)
Theorem production_funcall :
  forall fuel ge vargs m le0 le' m' v ty vres,
  bind_parameter_temps (fn_params production_f) vargs
    (create_undef_temps (fn_temps production_f)) = Some le0 ->
  run_mem_fuel fuel (genv_cenv ge) m (fn_body production_f) le0 =
    Some (le', (m', Out_return (Some (v, ty)))) ->
  sem_cast v ty (fn_return production_f) m' = Some vres ->
  ClightBigstep.eval_funcall function_entry2 ge m
    (Internal production_f) vargs E0 m' vres.
Proof.
  intros fuel ge vargs m le0 le' m' v ty vres BIND RUN CAST.
  eapply run_mem_fuel_funcall2 with
    (fuel := fuel) (le0 := le0) (le' := le') (v := v) (ty := ty).
  - vm_compute. reflexivity.
  - exact production_params_norepet.
  - exact production_params_temps_disjoint.
  - exact BIND.
  - vm_compute. discriminate.
  - exact RUN.
  - exact CAST.
Qed.

(** The exact production function has one parameter.  Define and check its
    initial temporary environment from the actual AST, rather than asking a
    caller to prove the binding side condition. *)
Definition production_le0 (arg: val) : temp_env :=
  match fn_params production_f with
  | (id, _) :: nil =>
      PTree.set id arg (create_undef_temps (fn_temps production_f))
  | _ => PTree.empty val
  end.

Lemma production_bind_one : forall arg,
  bind_parameter_temps (fn_params production_f) (arg :: nil)
    (create_undef_temps (fn_temps production_f)) =
  Some (production_le0 arg).
Proof. intro arg. vm_compute. reflexivity. Qed.

(** Fast, zero-default shadow execution of the exact production AST.  Bind
    the shadow pointer to the block that CompCert actually assigns [_cells];
    a fixed block number would leave the final memory theorem disconnected
    from the generated program's global environment. *)
Definition production_array_block : block :=
  Eval vm_compute in
  match Genv.find_symbol (Genv.globalenv prog) _cells with
  | Some b => b
  | None => 1%positive
  end.
Definition production_array_bytes : Z := 2400536%Z.
Definition production_arg : val := Vptr production_array_block Ptrofs.zero.
Definition production_flat_initial : flat_state :=
  {{| flat_temps := production_le0 production_arg;
      flat_array := PTree.empty int64 |}}.

(** Compact literal execution of the production loop.  It deliberately uses
    CompCert [int64] operations and the exact flat byte-offset map: unlike a
    [Uint63] shadow, this agrees with the generated [uint64_t] code even when
    the suppressed-store sink cells wrap modulo 2^64. *)
Definition compact_cells : Type := flat_cells.
Definition cI (z: Z) : int64 := Int64.repr z.
Definition cbit (b: bool) : int64 := if b then cI 1 else cI 0.
Definition cbyte_offset (index: int64) : Z :=
  Ptrofs.unsigned
    (Ptrofs.mul (Ptrofs.repr 8) (Ptrofs.of_int64 index)).
Definition cget (a: compact_cells) (index: int64) : int64 :=
  flat_load a (cbyte_offset index).
Definition cset (a: compact_cells) (index value: int64) : compact_cells :=
  flat_store a (cbyte_offset index) value.

Fixpoint seed_cells (values: list Z) (index: Z) (a: compact_cells)
    : compact_cells :=
  match values with
  | nil => a
  | value :: rest =>
      seed_cells rest (index + 1) (flat_store a (8 * index) (cI value))
  end.

Definition production_primes : list Z :=
  2 :: 3 :: 5 :: 7 :: 11 :: 13 :: 17 :: 19 :: 23 :: 29 :: 31 :: 37 ::
  41 :: 43 :: 47 :: 53 :: 59 :: 61 :: 67 :: 71 :: 73 :: 79 :: 83 :: 89 ::
  97 :: 101 :: 103 :: 107 :: 109 :: 113 :: 127 :: 131 :: 137 :: 139 ::
  149 :: 151 :: 157 :: 163 :: 167 :: 173 :: 179 :: 181 :: 191 :: 193 ::
  197 :: 199 :: 211 :: 223 :: 227 :: 229 :: 233 :: 239 :: 241 :: 251 ::
  257 :: 263 :: 269 :: 271 :: 277 :: 281 :: 283 :: 293 :: 307 :: 311 ::
  313 :: 100001 :: nil.

Record mob_state : Type := {{
  mob_cells : compact_cells;
  mob_pos : int64;
  mob_neg : int64;
  mob_pi : int64;
  mob_p : int64;
  mob_j : int64
}}.

Definition production_mob_initial : mob_state :=
  {{| mob_cells := seed_cells production_primes 300001 (PTree.empty int64);
      mob_pos := cI 0; mob_neg := cI 0;
      mob_pi := cI 0; mob_p := cI 2; mob_j := cI 2 |}}.

(** This is intentionally a literal, assignment-for-assignment transcription
    of the exact Clight loop body, with dead temporaries represented by lets. *)
Definition production_mob_step_fields (t: int64) (a0: compact_cells)
    (pos neg pi p j: int64) : mob_state :=
  let v6 := cbit (Int64.ltu t (cI 202298)) in
  let v10 := cbit (Int64.ltu j (cI 100000)) in
  let v7 := Int64.mul v10 v6 in
  let v11 := Int64.mul v7 j in
  let v12 := Int64.sub (cI 1) v7 in
  let v13 := Int64.mul v12 (cI 200000) in
  let v8 := Int64.add v11 v13 in
  let v9 := Int64.add v8 (cI 100000) in
  let v14 := cget a0 v8 in
  let v15 := cbit (Int64.eq v14 (cI 0)) in
  let v16 := Int64.add v14 v15 in
  let v17 := Int64.mul v16 p in
  let a1 := cset a0 v8 v17 in
  let v18 := cget a1 v9 in
  let v19 := Int64.mul p p in
  let v20 := Int64.modu v8 v19 in
  let v21 := cbit (Int64.eq v20 (cI 0)) in
  let v22 := Int64.xor v18 (cI 1) in
  let v23 := Int64.mul v21 (cI 2) in
  let v24 := Int64.or v22 v23 in
  let a2 := cset a1 v9 v24 in
  let v25 := Int64.sub (cI 1) v7 in
  let v26 := Int64.mul v6 v25 in
  let v27 := Int64.add pi v26 in
  let v28 := cbit (Int64.ltu (cI 65) v27) in
  let v29 := Int64.sub (cI 1) v28 in
  let v30 := Int64.mul v29 v27 in
  let v31 := Int64.mul v28 (cI 65) in
  let pi' := Int64.add v30 v31 in
  let v32 := Int64.add pi' (cI 300001) in
  let v33 := cget a2 v32 in
  let v34 := Int64.sub (cI 1) v26 in
  let v35 := Int64.add j p in
  let v36 := Int64.mul v26 v33 in
  let v37 := Int64.mul v34 p in
  let p' := Int64.add v36 v37 in
  let v38 := Int64.mul v26 p' in
  let v39 := Int64.mul v34 v35 in
  let j' := Int64.add v38 v39 in
  let v40 := Int64.sub t (cI 202298) in
  let v41 := Int64.sub (cI 1) v6 in
  let v42 := Int64.mul v41 v40 in
  let v43 := Int64.add v42 (cI 100000) in
  let v44 := cget a2 v42 in
  let v45 := cbit (Int64.eq v44 (cI 0)) in
  let v46 := Int64.add v44 v45 in
  let v47 := cget a2 v43 in
  let v48 := Int64.shru v47 (cI 1) in
  let v49 := Int64.and v48 (cI 1) in
  let v50 := Int64.and v47 (cI 1) in
  let v51 := cbit (negb (Int64.eq v46 v42)) in
  let v52 := Int64.xor v50 v51 in
  let v53 := Int64.sub (cI 1) v49 in
  let v54 := Int64.sub (cI 1) v52 in
  let v55 := Int64.mul v53 v54 in
  let v56 := Int64.mul v53 v52 in
  let v57 := Int64.mul v41 v55 in
  let v58 := Int64.mul v41 v56 in
  {{| mob_cells := a2;
      mob_pos := Int64.add pos v57;
      mob_neg := Int64.add neg v58;
      mob_pi := pi'; mob_p := p'; mob_j := j' |}}.

Definition production_mob_step (t: int64) (s: mob_state) : mob_state :=
  match s with
  | Build_mob_state a pos neg pi p j =>
      production_mob_step_fields t a pos neg pi p j
  end.

(** Every partial operation performed by one literal step.  Keeping this
    certificate executable lets the kernel check all 302,298 iterations,
    while the refinement theorem below may use the corresponding facts for
    Clight's checked loads, stores, remainder, and shift operations. *)
Definition cindex_ok (index: int64) : bool :=
  flat_offset_ok production_array_bytes (cbyte_offset index).

Definition production_mob_step_safe_fields (t: int64)
    (pos neg pi p j: int64) : bool :=
  let v6 := cbit (Int64.ltu t (cI 202298)) in
  let v10 := cbit (Int64.ltu j (cI 100000)) in
  let v7 := Int64.mul v10 v6 in
  let v11 := Int64.mul v7 j in
  let v12 := Int64.sub (cI 1) v7 in
  let v13 := Int64.mul v12 (cI 200000) in
  let v8 := Int64.add v11 v13 in
  let v9 := Int64.add v8 (cI 100000) in
  let v19 := Int64.mul p p in
  let v25 := Int64.sub (cI 1) v7 in
  let v26 := Int64.mul v6 v25 in
  let v27 := Int64.add pi v26 in
  let v28 := cbit (Int64.ltu (cI 65) v27) in
  let v29 := Int64.sub (cI 1) v28 in
  let v30 := Int64.mul v29 v27 in
  let v31 := Int64.mul v28 (cI 65) in
  let pi' := Int64.add v30 v31 in
  let v32 := Int64.add pi' (cI 300001) in
  let v40 := Int64.sub t (cI 202298) in
  let v41 := Int64.sub (cI 1) v6 in
  let v42 := Int64.mul v41 v40 in
  let v43 := Int64.add v42 (cI 100000) in
  cindex_ok v8 && cindex_ok v9 &&
  negb (Int64.eq v19 (cI 0)) && cindex_ok v32 &&
  cindex_ok v42 && cindex_ok v43.

Definition production_mob_step_safe (t: int64) (s: mob_state) : bool :=
  match s with
  | Build_mob_state _ pos neg pi p j =>
      production_mob_step_safe_fields t pos neg pi p j
  end.

Definition checked_mob_step (t: int64) (s: mob_state) : option mob_state :=
  if production_mob_step_safe t s
  then Some (production_mob_step t s)
  else None.

(** Binary recursion executes [n] sequential iterations with logarithmic
    recursion depth, avoiding a 302,298-constructor Peano fuel term. *)
Fixpoint run_mob_pos (n: positive) (start: int64) (s: mob_state)
    : mob_state :=
  match n with
  | xH => production_mob_step start s
  | xO half =>
      let mid := run_mob_pos half start s in
      run_mob_pos half (Int64.add start (cI (Z.pos half))) mid
  | xI half =>
      let mid := run_mob_pos half start s in
      let almost := run_mob_pos half
        (Int64.add start (cI (Z.pos half))) mid in
      production_mob_step
        (Int64.add start (cI (2 * Z.pos half))) almost
  end.

Fixpoint checked_run_mob_pos (n: positive) (start: int64) (s: mob_state)
    : option mob_state :=
  match n with
  | xH => checked_mob_step start s
  | xO half =>
      match checked_run_mob_pos half start s with
      | Some mid => checked_run_mob_pos half
          (Int64.add start (cI (Z.pos half))) mid
      | None => None
      end
  | xI half =>
      match checked_run_mob_pos half start s with
      | Some mid =>
          match checked_run_mob_pos half
              (Int64.add start (cI (Z.pos half))) mid with
          | Some almost => checked_mob_step
              (Int64.add start (cI (2 * Z.pos half))) almost
          | None => None
          end
      | None => None
      end
  end.

Definition production_mob_final : mob_state :=
  run_mob_pos 302298%positive (cI 0) production_mob_initial.

Definition production_mob_answer : Z :=
  100001 + Int64.unsigned production_mob_final.(mob_pos) -
    Int64.unsigned production_mob_final.(mob_neg).

Theorem production_candidate_computes_99952 :
  production_mob_answer = 99952.
Proof. vm_compute. reflexivity. Qed.

Theorem production_candidate_all_steps_safe :
  checked_run_mob_pos 302298%positive (cI 0) production_mob_initial =
  Some production_mob_final.
Proof. vm_compute. reflexivity. Qed.

(** The exact generated global is a writable, zero-filled array without
    reducing [Genv.init_mem]. *)
Lemma production_cells_metadata :
  exists b,
    Genv.find_symbol (Genv.globalenv prog) _cells = Some b /\
    Genv.find_var_info (Genv.globalenv prog) b = Some v_cells.
Proof. vm_compute. eexists; split; reflexivity. Qed.

Theorem production_zero_global_rel : forall m b,
  Genv.find_var_info (Genv.globalenv prog) b = Some v_cells ->
  Genv.init_mem prog = Some m ->
  flat_block_rel (PTree.empty int64) m b production_array_bytes.
Proof.
  intros m b FIND INIT.
  eapply (@init_space_flat_block_rel fundef type prog b v_cells m
    production_array_bytes).
  - exact FIND.
  - exact INIT.
  - vm_compute. reflexivity.
  - vm_compute. reflexivity.
  - vm_compute. reflexivity.
Qed.

(** Fully specialized function endpoint.  Parameter binding and the return
    cast are discharged from the exact AST.  The sole remaining premise is
    the artifact-specific successful-run certificate. *)
Theorem production_funcall_from_run :
  forall fuel ge m arg le' m' n,
  run_mem_fuel fuel (genv_cenv ge) m (fn_body production_f)
    (production_le0 arg) =
      Some (le', (m', Out_return (Some (Vlong n, tulong)))) ->
  ClightBigstep.eval_funcall function_entry2 ge m
    (Internal production_f) (arg :: nil) E0 m' (Vlong n).
Proof.
  intros fuel ge m arg le' m' n RUN.
  eapply production_funcall with
    (fuel := fuel) (le0 := production_le0 arg) (le' := le')
    (v := Vlong n) (ty := tulong).
  - apply production_bind_one.
  - exact RUN.
  - vm_compute. reflexivity.
Qed.
'''


def flags(compcert: Path, outdir: Path):
    result = []
    for sub, logical in [
        ("lib", "compcert.lib"), ("common", "compcert.common"),
        ("aarch64", "compcert.aarch64"), ("backend", "compcert.backend"),
        ("cfrontend", "compcert.cfrontend"), ("driver", "compcert.driver"),
        ("cparser", "compcert.cparser"), ("export", "compcert.export"),
        ("flocq", "Flocq"), ("MenhirLib", "MenhirLib"),
    ]:
        result += ["-R", str(compcert / sub), logical]
    return result + ["-Q", str(outdir), "Direct"]


def compile_v(coqc: str, coq_flags, outdir: Path, name: str):
    proc = subprocess.run([coqc, *coq_flags, name], cwd=outdir,
                          text=True, capture_output=True)
    if proc.returncode:
        sys.stdout.write(proc.stdout)
        sys.stderr.write(proc.stderr)
        raise SystemExit(f"error: coqc rejected {name}")
    print(f"[ok] {name}")


def main():
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument("clight_v", type=Path)
    parser.add_argument("function", help="Coq function constant, e.g. f_l_ArrayMobius_rolled100k")
    parser.add_argument("outdir", type=Path)
    parser.add_argument("--compcert", type=Path, default=Path(DEFAULT_COMPCERT))
    parser.add_argument("--coqc", default=DEFAULT_COQC)
    args = parser.parse_args()

    outdir = args.outdir.resolve()
    outdir.mkdir(parents=True, exist_ok=True)
    source_dir = Path(__file__).resolve().parent / "coq"
    shutil.copyfile(args.clight_v.resolve(), outdir / "ArrayCert.v")
    shutil.copyfile(source_dir / "ClightMemorySem.v", outdir / "ClightMemorySem.v")
    shutil.copyfile(source_dir / "ClightFlatSem.v", outdir / "ClightFlatSem.v")
    shutil.copyfile(source_dir / "ArrayMobiusStaged.v",
                    outdir / "ArrayMobiusStaged.v")
    (outdir / "ArrayCheck.v").write_text(CHECK.format(function=args.function))

    coq_flags = flags(args.compcert.resolve(), outdir)
    compile_v(args.coqc, coq_flags, outdir, "ClightMemorySem.v")
    compile_v(args.coqc, coq_flags, outdir, "ClightFlatSem.v")
    compile_v(args.coqc, coq_flags, outdir, "ArrayCert.v")
    compile_v(args.coqc, coq_flags, outdir, "ArrayCheck.v")
    compile_v(args.coqc, coq_flags, outdir, "ArrayMobiusStaged.v")
    print("RESULT: PASS (exact production array AST bound to CompCert semantics)")


if __name__ == "__main__":
    main()
