#!/usr/bin/env python3
"""clight-direct-verify.py -- certify a directly-emitted Clight certificate.

Takes a directly-emitted Clight .v file (goto-free fragment: Sset /
Ssequence / Sreturn over Etempvar / Econst_int / Econst_long / Ebinop /
Ecast), an expected u64 return value, and a work directory.  It:

  1. copies the certificate into the workdir under the fixed module name
     DirectFP.v (a valid Coq module name),
  2. compiles (with caching) the once-and-for-all development
     ClightFragmentSem.v (computable evaluator `run` + Qed-proved
     soundness against CompCert's ClightBigstep semantics),
  3. compiles (with caching) DirectFP.v,
  4. generates DirectFPCheck.v, which vm_computes the body under `run`
     and derives, via the soundness theorems:
       - fp_bigstep : forall fe ge e m, exec_stmt ... E0 ... m
                        (Out_return (Some (Vlong (Int64.repr N), tulong)))
       - fp_funcall : forall ge m, eval_funcall function_entry2 ge m
                        (Internal f) nil E0 m (Vlong (Int64.repr N))
  5. compiles it; exit 0 iff every file Qed-checks.

A wrong expected value makes the vm_compute reflexivity check fail, so
the script exits nonzero (see --self-test for a demonstration).

Usage:
  clight-direct-verify.py DIRECT_V EXPECTED_U64 WORKDIR
      [--function NAME] [--compcert DIR] [--coqc PATH] [--self-test]
"""

import argparse
import hashlib
import os
import re
import shutil
import subprocess
import sys
import time
from pathlib import Path

DEFAULT_COMPCERT = os.environ.get("COMPCERT_DIR", "/home/gersh/CompCert-3.17")
DEFAULT_COQC = os.environ.get("COQC", "/home/gersh/.opam/4.14.2/bin/coqc")

CHECK_TEMPLATE = """(* Auto-generated by clight-direct-verify.py -- do not edit. *)
From compcert Require Import Coqlib Maps Integers Values Events Memory.
From compcert Require Import AST Ctypes Cop Clight ClightBigstep Clightdefs.
Require Import Direct.DirectFP Direct.ClightFragmentSem.

Definition fp_f : function := {func}.
Definition fp_le0 : temp_env := create_undef_temps (fn_temps fp_f).
Definition fp_expected : val := Vlong (Int64.repr {expected}).

(* Closed computation: vm_compute-friendly (no existential). *)
Lemma fp_run_ret :
  run_ret (PTree.empty composite) Mem.empty (fn_body fp_f) fp_le0
    = Some (fp_expected, tulong).
Proof. vm_compute. reflexivity. Qed.

Lemma fp_semantics : exists le',
  run (PTree.empty composite) Mem.empty (fn_body fp_f) fp_le0
    = Some (le', Out_return (Some (fp_expected, tulong))).
Proof. exact (run_ret_run _ _ _ _ _ fp_run_ret). Qed.

(* Statement-level big-step conclusion: for EVERY function-entry family
   fe, genv ge, env e and memory m, the body executes with trace E0,
   leaves the memory unchanged, and returns fp_expected at tulong. *)
Theorem fp_bigstep : forall fe ge e m, exists le',
  ClightBigstep.exec_stmt fe ge e fp_le0 m (fn_body fp_f) E0 le' m
    (Out_return (Some (fp_expected, tulong))).
Proof.
  intros fe ge e m.
  destruct (run_ret_run _ _ _ _ _ fp_run_ret) as [le' Hrun].
  exists le'.
  apply run_sound.
  rewrite (run_indep (fn_body fp_f) (genv_cenv ge) (PTree.empty composite)
                     m Mem.empty fp_le0).
  exact Hrun.
Qed.

(* Function-level big-step conclusion (Clight2 / function_entry2). *)
Theorem fp_funcall : forall ge m,
  ClightBigstep.eval_funcall function_entry2 ge m (Internal fp_f) nil E0 m
    fp_expected.
Proof.
  intros ge m.
  destruct (run_ret_run _ _ _ _ _ fp_run_ret) as [le' Hrun].
  eapply run_funcall2 with (v := fp_expected) (ty := tulong).
  - reflexivity.
  - reflexivity.
  - intro Hc; discriminate Hc.
  - rewrite (run_indep (fn_body fp_f) (genv_cenv ge) (PTree.empty composite)
                       m Mem.empty (create_undef_temps (fn_temps fp_f))).
    exact Hrun.
  - reflexivity.
Qed.
"""


def coq_flags(compcert: str, workdir: Path):
    cc = compcert
    flags = []
    for sub, logical in [
        ("lib", "compcert.lib"), ("common", "compcert.common"),
        ("aarch64", "compcert.aarch64"), ("backend", "compcert.backend"),
        ("cfrontend", "compcert.cfrontend"), ("driver", "compcert.driver"),
        ("cparser", "compcert.cparser"), ("export", "compcert.export"),
        ("flocq", "Flocq"), ("MenhirLib", "MenhirLib"),
    ]:
        flags += ["-R", f"{cc}/{sub}", logical]
    flags += ["-Q", str(workdir), "Direct"]
    return flags


def compile_v(coqc: str, flags, workdir: Path, vfile: str, label: str) -> bool:
    t0 = time.monotonic()
    proc = subprocess.run(
        [coqc] + flags + [vfile],
        cwd=workdir, capture_output=True, text=True,
    )
    dt = time.monotonic() - t0
    if proc.returncode != 0:
        print(f"[FAIL] {label}: coqc failed in {dt:.2f}s")
        sys.stdout.write(proc.stdout)
        sys.stdout.write(proc.stderr)
        return False
    print(f"[ok]   {label}: compiled in {dt:.2f}s")
    return True


def cached_copy_and_compile(src: Path, dst: Path, coqc, flags, workdir, label) -> bool:
    """Copy src to dst if content differs; compile unless a .vo built from the
    same content with the same coqc and flags exists (stamp-keyed, so switching
    --coqc/--compcert never reuses a stale .vo)."""
    vo = dst.with_suffix(".vo")
    stamp = dst.with_suffix(".stamp")
    content = src.read_bytes()
    key = hashlib.sha256(
        b"\0".join([content, coqc.encode()] + [f.encode() for f in flags])
    ).hexdigest()
    if not dst.exists() or dst.read_bytes() != content:
        shutil.copyfile(src, dst)
    if vo.exists() and stamp.exists() and stamp.read_text().strip() == key:
        print(f"[ok]   {label}: cached ({vo.name} up to date)")
        return True
    if not compile_v(coqc, flags, workdir, dst.name, label):
        return False
    stamp.write_text(key + "\n")
    return True


def detect_function(text: str) -> str:
    m = re.search(r"Definition\s+(f_\w+)\s*:\s*function\b", text)
    if not m:
        sys.exit("error: could not find 'Definition f_<name> : function' "
                 "in the certificate; pass --function")
    return m.group(1)


def run_pipeline(direct_v: Path, expected: int, workdir: Path, func,
                 compcert: str, coqc: str, check_name="DirectFPCheck") -> bool:
    workdir = workdir.resolve()
    direct_v = direct_v.resolve()
    workdir.mkdir(parents=True, exist_ok=True)
    flags = coq_flags(compcert, workdir)

    text = direct_v.read_text()
    if func is None:
        func = detect_function(text)
    print(f"certificate: {direct_v}")
    print(f"function:    {func}")
    print(f"expected:    {expected} (u64)")
    print(f"workdir:     {workdir}")

    frag_src = Path(__file__).resolve().parent / "coq" / "ClightFragmentSem.v"
    if not frag_src.exists():
        sys.exit(f"error: {frag_src} not found")

    # 1. once-and-for-all development (cached)
    if not cached_copy_and_compile(frag_src, workdir / "ClightFragmentSem.v",
                                   coqc, flags, workdir, "ClightFragmentSem"):
        return False
    # 2. the certificate, under a fixed valid module name (cached)
    if not cached_copy_and_compile(direct_v, workdir / "DirectFP.v",
                                   coqc, flags, workdir, "DirectFP"):
        return False
    # 3. generated per-certificate check
    check = workdir / f"{check_name}.v"
    check.write_text(CHECK_TEMPLATE.format(func=func, expected=expected))
    return compile_v(coqc, flags, workdir, check.name,
                     f"{check_name} (vm_compute + soundness)")


def main():
    ap = argparse.ArgumentParser(description=__doc__.split("\n")[0])
    ap.add_argument("direct_v", type=Path, help="directly-emitted Clight .v")
    ap.add_argument("expected", type=int, help="expected u64 return value")
    ap.add_argument("workdir", type=Path, help="work directory (caches .vo)")
    ap.add_argument("--function", default=None,
                    help="Clight function name (default: autodetect f_*)")
    ap.add_argument("--compcert", default=DEFAULT_COMPCERT)
    ap.add_argument("--coqc", default=DEFAULT_COQC)
    ap.add_argument("--self-test", action="store_true",
                    help="also check that expected+1 FAILS (discrimination)")
    args = ap.parse_args()

    if not (0 <= args.expected < 2 ** 64):
        sys.exit("error: expected value out of u64 range")

    ok = run_pipeline(args.direct_v, args.expected, args.workdir,
                      args.function, args.compcert, args.coqc)
    if not ok:
        print("RESULT: FAIL")
        sys.exit(1)

    if args.self_test:
        wrong = (args.expected + 1) % (2 ** 64)
        print(f"--- discrimination self-test: expecting {wrong} must FAIL ---")
        bad = run_pipeline(args.direct_v, wrong, args.workdir,
                           args.function, args.compcert, args.coqc,
                           check_name="DirectFPCheckMutated")
        if bad:
            print("RESULT: FAIL (mutated expected value was accepted!)")
            sys.exit(1)
        print("[ok]   discrimination: mutated value rejected as required")

    print("RESULT: PASS")
    sys.exit(0)


if __name__ == "__main__":
    main()
