#!/usr/bin/env python3
"""Coq-mechanized structural correspondence: certificate C vs clightgen .v.

Usage:
  clight-correspond-coq.py [options] <cert.c> <cert.v> <outdir>
  clight-correspond-coq.py [options] --self-test <outdir>

This is the proof-level upgrade of scripts/clight-correspond.py (roadmap M6:
"proof-level correspondence in Coq/Lean rather than a checker").  The Python
checker parses BOTH sides itself and compares event streams in Python; here
only the C side is parsed by Python (reusing clight-correspond.py's C parser).
The Clight side is never re-parsed: the clightgen-produced .v file is compiled
by coqc against the real CompCert 3.17 Coq development, a generated Coq
`events` function (over CompCert's own `Clight.statement` AST) extracts the
structural event stream from `fn_body f_l_*`, and Coq's kernel checks

    Lemma correspondence_<f> : events (fn_body f_<f>) = expected_<f>.
    Proof. vm_cast_no_check (eq_refl expected_<f>). Qed.

where `expected_<f>` is the event list this script computes from the C file.
A Qed means CompCert's kernel-checked term -- the exact term CompCert's
correctness proof starts from -- has precisely the expected assignment/
operator/operand/control-flow stream.  The trusted base for the *comparison*
shrinks from a Python s-expression parser of .v text to: this script's C-side
parser + expected-list printer, the small generated Coq prelude below, and Coq
itself.

Generated files in <outdir>:
  Cert.v               verbatim copy of the certificate .v (module Cert)
  CorrespondPrelude.v  event type + `events : statement -> list ev`
  CorrespondCheck.v    expected event lists + correspondence lemmas
  probe.v/.vo, *.vo, Cert.stamp   build artifacts / cache

Exit status: 0 iff every lemma Qeds (and, under --self-test, iff the mutated
negative control FAILS to Qed).

HONESTY NOTE: like the Python checker this is *structural* translation
validation, not a semantics proof: casts are erased on both sides, evaluation
order/overflow/memory are not modeled, and the C-side event extraction is
still Python.  What is new is that the .v side is no longer parsed by a
regex/s-expression walker: Coq elaborates the certificate term itself and the
kernel validates the equality.

LIMITATIONS:
  * C-side parsing limitations are inherited from clight-correspond.py
    (emitter-shaped C only; see its docstring).
  * A C `while` is matched against the exact `Clight.Swhile` unfolding
    (Sloop (Ssequence (Sifthenelse c Sskip Sbreak) body) Sskip), which is what
    clightgen -normalize emits; a rolled `Sloop` of any other shape extracts
    as `ELoop None` and will NOT match a C while (stricter than the Python
    checker, which let a bare Sloop match any condition).
  * Calls are compared as full `ECall` events -- result destination, callee
    ident, and every argument descriptor in order (`v = f(a);` maps to
    Clight's `Scall (Some _v) (Evar _f _) [a]`).  Calls nested inside larger
    expressions are rejected: Clight has no call expression and the emitter's
    certificate fragment never produces them.
  * `Econst_float`/`Econst_single` and address-of/deref/field expressions
    extract as `Dunknown`, and `Sassign`/`Sbuiltin`/`Sswitch` as `EOther`:
    the expected list never contains these, so any occurrence FAILS the
    proof (conservative, mirrors the Python checker's parse errors).
"""

from __future__ import annotations

import argparse
import glob
import hashlib
import importlib.util
import os
import re
import shutil
import subprocess
import sys
import time

DEFAULT_COMPCERT = os.environ.get("COMPCERT_DIR", "/home/gersh/CompCert-3.17")

# Fallback mirror of CompCert 3.17's _CoqProject -R lines.
DEFAULT_MAPPINGS = [
    ("lib", "compcert.lib"), ("common", "compcert.common"),
    ("aarch64", "compcert.aarch64"), ("backend", "compcert.backend"),
    ("cfrontend", "compcert.cfrontend"), ("driver", "compcert.driver"),
    ("cparser", "compcert.cparser"), ("export", "compcert.export"),
    ("flocq", "Flocq"), ("MenhirLib", "MenhirLib"),
]

PRELUDE = '''\
(* Structural correspondence event extraction over CompCert Clight statements.
   Generated by scripts/clight-correspond-coq.py -- do not edit. *)
From Coq Require Import String List ZArith.
From compcert Require Import Coqlib Integers AST Ctypes Cop Clight Clightdefs.
Import ListNotations.

(* Normalized expression descriptor (casts erased; mirrors the descriptor
   space of scripts/clight-correspond.py). *)
Inductive dsc : Type :=
| Dvar (x : ident)
| Dlit (width : nat) (value : Z)
| Dbin (op : Cop.binary_operation) (l r : dsc)
| Dun (op : Cop.unary_operation) (a : dsc)
| Dunknown.

(* Ordered structural event. *)
Inductive ev : Type :=
| EAssign (dest : ident) (rhs : dsc)
| ELoop (cond : option dsc)
| EEndLoop
| EIf (cond : dsc)
| EElse
| EEndIf
| ELabel (l : ident)
| EGoto (l : ident)
| EReturn (r : option dsc)
| ECall (dst : option ident) (f : ident) (args : list dsc)
| EOther.

Fixpoint dsc_of_expr (e : Clight.expr) : dsc :=
  match e with
  | Ecast e' _ => dsc_of_expr e'          (* casts erased on both sides *)
  | Etempvar x _ => Dvar x
  | Evar x _ => Dvar x
  | Econst_int i _ => Dlit 32 (Int.unsigned i)
  | Econst_long i _ => Dlit 64 (Int64.unsigned i)
  | Ebinop op l r _ => Dbin op (dsc_of_expr l) (dsc_of_expr r)
  | Eunop op a _ => Dun op (dsc_of_expr a)
  | _ => Dunknown                          (* never expected: forces FAIL *)
  end.

(* Event stream of a Clight statement.  An [Sloop] in the exact shape of
   [Clight.Swhile]'s unfolding (what clightgen emits for a C [while])
   recovers the loop condition; any other [Sloop] yields [ELoop None]. *)
Fixpoint events (s : Clight.statement) : list ev :=
  match s with
  | Sskip | Sbreak | Scontinue => []
  | Sassign _ _ => [EOther]
  | Sset dst e => [EAssign dst (dsc_of_expr e)]
  | Scall dst (Evar f _) args => [ECall dst f (map dsc_of_expr args)]
  | Scall _ _ _ => [EOther]
  | Sbuiltin _ _ _ _ => [EOther]
  | Ssequence s1 s2 => events s1 ++ events s2
  | Sifthenelse c s1 s2 =>
      EIf (dsc_of_expr c) :: events s1 ++ EElse :: events s2 ++ [EEndIf]
  | Sloop (Ssequence (Sifthenelse c Sskip Sbreak) body) Sskip =>
      ELoop (Some (dsc_of_expr c)) :: events body ++ [EEndLoop]
  | Sloop s1 s2 => ELoop None :: events s1 ++ events s2 ++ [EEndLoop]
  | Sreturn None => [EReturn None]
  | Sreturn (Some e) => [EReturn (Some (dsc_of_expr e))]
  | Sswitch _ _ => [EOther]
  | Slabel l s1 => ELabel l :: events s1
  | Sgoto l => [EGoto l]
  end.
'''

MINI_C = '''\
#include <stdint.h>

uint64_t l_help(uint64_t x)
{
    return x + UINT64_C(1);
}

uint64_t l_mini(void)
{
    uint64_t v_0;
    uint64_t v_1;
    uint64_t v_2;
    v_0 = UINT64_C(2);
    v_1 = v_0 + UINT64_C(3);
    l_help(v_1);
    v_2 = v_1 * v_0;
    return v_2;
}
'''


class GenError(Exception):
    pass


def load_c_parser():
    """Import scripts/clight-correspond.py (hyphenated name) as a module."""
    path = os.path.join(os.path.dirname(os.path.abspath(__file__)),
                        "clight-correspond.py")
    spec = importlib.util.spec_from_file_location("clight_correspond", path)
    mod = importlib.util.module_from_spec(spec)
    sys.modules["clight_correspond"] = mod   # required for @dataclass
    spec.loader.exec_module(mod)
    return mod


# --------------------------------------------------------------------------
# coqc discovery and flags
# --------------------------------------------------------------------------

def compcert_flags(compcert_dir):
    """-R/-Q flags for the compiled CompCert tree, from its _CoqProject."""
    mappings, proj = [], os.path.join(compcert_dir, "_CoqProject")
    if os.path.exists(proj):
        toks = open(proj).read().split()
        i = 0
        while i < len(toks):
            if toks[i] in ("-R", "-Q") and i + 2 < len(toks):
                mappings.append((toks[i], toks[i + 1], toks[i + 2]))
                i += 3
            else:
                i += 1
    else:
        mappings = [("-R", d, l) for d, l in DEFAULT_MAPPINGS]
    flags = []
    for opt, subdir, logical in mappings:
        physical = os.path.join(compcert_dir, subdir)
        if os.path.isdir(physical):
            flags += [opt, physical, logical]
    if not flags:
        raise GenError(f"no CompCert subdirectories found under {compcert_dir}")
    return flags


def find_coqc(explicit, flags, outdir):
    """Probe candidate coqc binaries: the first that can Require CompCert's
    compiled Clight wins (this catches .vo version mismatches empirically)."""
    if explicit:
        candidates = [explicit]
    else:
        candidates = []
        if os.environ.get("COQC"):
            candidates.append(os.environ["COQC"])
        candidates.append("coqc")
        candidates += sorted(glob.glob(os.path.expanduser("~/.opam/*/bin/coqc")))
    probe = os.path.join(outdir, "probe.v")
    with open(probe, "w") as fh:
        fh.write("From compcert Require Import Clight.\n")
    tried = []
    for cand in candidates:
        if shutil.which(cand) is None and not os.access(cand, os.X_OK):
            tried.append(f"{cand}: not found")
            continue
        r = subprocess.run([cand] + flags + [probe],
                           capture_output=True, text=True)
        if r.returncode == 0:
            ver_lines = subprocess.run(
                [cand, "--version"], capture_output=True, text=True
            ).stdout.splitlines()
            return cand, ver_lines[0] if ver_lines else "unknown version"
        tried.append(f"{cand}: {r.stderr.strip().splitlines()[-1] if r.stderr.strip() else 'failed'}")
    raise GenError("no working coqc found (needs the Coq version the CompCert "
                   ".vo files were built with).  Tried:\n  " + "\n  ".join(tried))


# --------------------------------------------------------------------------
# Expected-list generation (C events -> Coq terms)
# --------------------------------------------------------------------------

IDENT_DEF_RE = re.compile(r'^Definition\s+(_[A-Za-z0-9_\']*)\s*:\s*ident\s*:=\s*'
                          r'\$"([^"]*)"\s*\.', re.M)
FUNC_DEF_RE = re.compile(r'^Definition\s+f_(l_\w+)\s*:=\s*\{\|', re.M)


def ident_map_of_v(v_text):
    """Map C-level name -> Coq ident constant, read from the certificate .v's
    `Definition _x : ident := $"x".` lines (the same constants clightgen uses
    inside fn_body, so referencing them by name is exact)."""
    return {cname: coqname for coqname, cname in IDENT_DEF_RE.findall(v_text)}


class ExpectedPrinter:
    def __init__(self, ident_map, func):
        self.ident_map = ident_map
        self.func = func

    def ident(self, cname):
        try:
            return self.ident_map[cname]
        except KeyError:
            raise GenError(
                f"{self.func}: C name {cname!r} has no `Definition _{cname} : "
                f"ident := $\"{cname}\".` in the certificate .v")

    def dsc(self, d):
        kind = d[0]
        if kind == "var":
            return f"(Dvar {self.ident(d[1])})"
        if kind == "lit":
            _, value, width = d
            return f"(Dlit {width} {value})"
        if kind == "bin":
            return f"(Dbin {d[1]} {self.dsc(d[2])} {self.dsc(d[3])})"
        if kind == "un":
            return f"(Dun {d[1]} {self.dsc(d[2])})"
        if kind == "call":
            raise GenError(f"{self.func}: call expression {d[1]}(...) in an "
                           "assignment is not representable in Clight events")
        raise GenError(f"{self.func}: unknown C descriptor {d!r}")

    def event(self, e):
        kind = e[0]
        if kind == "assign":
            return f"EAssign {self.ident(e[1])} {self.dsc(e[2])}"
        if kind == "loop":
            return f"ELoop (Some {self.dsc(e[1])})"
        if kind == "endloop":
            return "EEndLoop"
        if kind == "if":
            return f"EIf {self.dsc(e[1])}"
        if kind == "else":
            return "EElse"
        if kind == "endif":
            return "EEndIf"
        if kind == "label":
            return f"ELabel {self.ident(e[1])}"
        if kind == "goto":
            return f"EGoto {self.ident(e[1])}"
        if kind == "return":
            return "EReturn None" if e[1] is None \
                else f"EReturn (Some {self.dsc(e[1])})"
        if kind == "call":
            _, name, dest, args = e
            dst = "None" if dest is None else f"(Some {self.ident(dest)})"
            arg_list = "[" + "; ".join(self.dsc(a) for a in args) + "]"
            return f"ECall {dst} {self.ident(name)} {arg_list}"
        raise GenError(f"{self.func}: unknown C event {e!r}")


def check_file_text(c_funcs, ident_map):
    out = ["(* Expected structural event lists (computed from the certificate",
           "   C file) and kernel-checked correspondence lemmas.",
           "   Generated by scripts/clight-correspond-coq.py -- do not edit. *)",
           "From Coq Require Import String List ZArith.",
           "From compcert Require Import Coqlib Integers AST Ctypes Cop "
           "Clight Clightdefs.",
           "From Correspond Require Import CorrespondPrelude Cert.",
           "Import ListNotations.",
           "Local Open Scope Z_scope.",
           ""]
    for name, cf in c_funcs.items():
        pr = ExpectedPrinter(ident_map, name)
        lines = [pr.event(e) for e in cf.events]
        out.append(f"Definition expected_{name} : list ev :=")
        out.append("  [" + ";\n   ".join(lines) + "].")
        out.append("")
        out.append(f"Lemma correspondence_{name} :")
        out.append(f"  events (fn_body f_{name}) = expected_{name}.")
        out.append(f"Proof. vm_cast_no_check (eq_refl expected_{name}). Qed.")
        out.append("")
    return "\n".join(out)


# --------------------------------------------------------------------------
# Build driver
# --------------------------------------------------------------------------

def run_coqc(coqc, flags, path, label):
    t0 = time.monotonic()
    r = subprocess.run([coqc] + flags + [path], capture_output=True, text=True)
    dt = time.monotonic() - t0
    return r, dt


def check_pair(cc_mod, c_path, v_path, outdir, coqc, flags, quiet_fail=False):
    """Generate + compile + prove.  Returns 0 on full success, 1 when the
    correspondence lemma itself is rejected by Coq (the discrimination case),
    and 2 on infrastructure failure (certificate or prelude did not compile).
    The self-test's negative control accepts only 1, so a broken environment
    cannot masquerade as a rejected mutant."""
    c_text = open(c_path).read()
    v_text = open(v_path).read()
    c_funcs = cc_mod.parse_c_functions(c_text)
    if not c_funcs:
        raise GenError(f"no l_* certificate function found in {c_path}")
    v_func_names = set(FUNC_DEF_RE.findall(v_text))
    missing = sorted(set(c_funcs) - v_func_names)
    if missing:
        raise GenError(f"{v_path} lacks Definition f_<name> for: {missing}")
    extra = sorted(v_func_names - set(c_funcs))
    if extra:
        raise GenError(f"{v_path} defines certificate functions absent from "
                       f"the C file (would go unchecked): {extra}")
    ident_map = ident_map_of_v(v_text)

    cert_v = os.path.join(outdir, "Cert.v")
    shutil.copyfile(v_path, cert_v)
    with open(os.path.join(outdir, "CorrespondPrelude.v"), "w") as fh:
        fh.write(PRELUDE)
    with open(os.path.join(outdir, "CorrespondCheck.v"), "w") as fh:
        fh.write(check_file_text(c_funcs, ident_map))

    local_flags = flags + ["-Q", outdir, "Correspond"]

    # Cert.v can be large; cache its .vo keyed on content + toolchain.
    stamp_path = os.path.join(outdir, "Cert.stamp")
    key = hashlib.sha256(("\0".join([v_text, coqc] + local_flags))
                         .encode()).hexdigest()
    cert_vo = os.path.join(outdir, "Cert.vo")
    if os.path.exists(cert_vo) and os.path.exists(stamp_path) \
            and open(stamp_path).read().strip() == key:
        print(f"  Cert.v: cached ({os.path.basename(v_path)} unchanged)")
    else:
        r, dt = run_coqc(coqc, local_flags, cert_v, "Cert.v")
        if r.returncode != 0:
            print(f"  FAIL: coqc could not compile the certificate .v "
                  f"({dt:.1f}s):\n{r.stderr}", file=sys.stderr)
            return 2
        print(f"  Cert.v: compiled in {dt:.1f}s "
              f"({os.path.getsize(cert_v)} bytes)")
        with open(stamp_path, "w") as fh:
            fh.write(key + "\n")

    r, dt = run_coqc(coqc, local_flags,
                     os.path.join(outdir, "CorrespondPrelude.v"), "prelude")
    if r.returncode != 0:
        print(f"  FAIL: prelude did not compile ({dt:.1f}s):\n{r.stderr}",
              file=sys.stderr)
        return 2
    print(f"  CorrespondPrelude.v: compiled in {dt:.1f}s")

    r, dt = run_coqc(coqc, local_flags,
                     os.path.join(outdir, "CorrespondCheck.v"), "check")
    if r.returncode != 0:
        if not quiet_fail:
            print(f"  FAIL: correspondence lemma rejected by Coq ({dt:.1f}s):"
                  f"\n{r.stderr}", file=sys.stderr)
        else:
            print(f"  correspondence lemma rejected by Coq ({dt:.1f}s) "
                  "[expected for negative control]")
        return 1
    for name, cf in c_funcs.items():
        ops = [e[2][1] for e in cf.events
               if e[0] == "assign" and e[2][0] == "bin"]
        print(f"  {name}: Qed -- {len(cf.events)} structural events "
              f"kernel-checked ({len(ops)} binary ops)")
    print(f"  CorrespondCheck.v: proved in {dt:.1f}s")
    return 0


def self_test(cc_mod, outdir, coqc, flags):
    """Positive + negative control on a generated mini certificate."""
    st_dir = os.path.join(outdir, "selftest")
    os.makedirs(st_dir, exist_ok=True)
    mini_c = os.path.join(st_dir, "mini.c")
    with open(mini_c, "w") as fh:
        fh.write(MINI_C)
    r = subprocess.run(["clightgen", "-normalize", mini_c],
                       capture_output=True, text=True, cwd=st_dir)
    if r.returncode != 0:
        raise GenError(f"clightgen failed on the self-test file:\n{r.stderr}")
    mini_v = os.path.join(st_dir, "mini.v")

    print("self-test positive control (mini certificate):")
    pos_dir = os.path.join(st_dir, "pos")
    os.makedirs(pos_dir, exist_ok=True)
    if check_pair(cc_mod, mini_c, mini_v, pos_dir, coqc, flags) != 0:
        print("SELF-TEST RESULT: FAIL (positive control did not prove)")
        return 1

    print("self-test negative control (Oadd mutated to Osub in the .v):")
    mut_v = os.path.join(st_dir, "mini-mutated.v")
    v_text = open(mini_v).read()
    if "Ebinop Oadd" not in v_text:
        raise GenError("self-test .v has no Ebinop Oadd to mutate")
    with open(mut_v, "w") as fh:
        fh.write(v_text.replace("Ebinop Oadd", "Ebinop Osub", 1))
    neg_dir = os.path.join(st_dir, "neg")
    os.makedirs(neg_dir, exist_ok=True)
    rc = check_pair(cc_mod, mini_c, mut_v, neg_dir, coqc, flags,
                    quiet_fail=True)
    if rc == 0:
        print("SELF-TEST RESULT: FAIL (mutated .v was wrongly accepted)")
        return 1
    if rc != 1:
        print("SELF-TEST RESULT: FAIL (negative control hit an "
              "infrastructure failure, not a lemma rejection)")
        return 1
    print("SELF-TEST RESULT: PASS (genuine pair proved; mutant rejected)")
    return 0


def main(argv):
    ap = argparse.ArgumentParser(
        description="Kernel-checked structural correspondence between a "
                    "certificate C file and its clightgen .v output.")
    ap.add_argument("cert_c", nargs="?", help="certificate C file")
    ap.add_argument("cert_v", nargs="?", help="clightgen output .v file")
    ap.add_argument("outdir", nargs="?", help="working/output directory")
    ap.add_argument("--compcert", default=DEFAULT_COMPCERT,
                    help="compiled CompCert Coq development "
                         f"(default: {DEFAULT_COMPCERT})")
    ap.add_argument("--coqc", default=None,
                    help="coqc binary (default: probe $COQC, PATH, opam "
                         "switches for one matching the .vo version)")
    ap.add_argument("--self-test", action="store_true",
                    help="run positive+negative controls on a generated mini "
                         "certificate (only <outdir> is required)")
    args = ap.parse_args(argv[1:])

    if args.self_test:
        if args.outdir is None:
            args.outdir = args.cert_c   # allow `--self-test OUTDIR` form
        if args.outdir is None or args.cert_v is not None:
            ap.error("--self-test takes exactly one directory argument")
    elif not (args.cert_c and args.cert_v and args.outdir):
        ap.error("cert_c, cert_v and outdir are required (or use --self-test)")

    outdir = os.path.abspath(args.outdir)
    os.makedirs(outdir, exist_ok=True)
    cc_mod = load_c_parser()
    try:
        flags = compcert_flags(os.path.abspath(args.compcert))
        coqc, ver = find_coqc(args.coqc, flags, outdir)
        print(f"coqc: {coqc} ({ver})")
        if args.self_test:
            return self_test(cc_mod, outdir, coqc, flags)
        print(f"checking {args.cert_c} against {args.cert_v}:")
        rc = check_pair(cc_mod, args.cert_c, os.path.abspath(args.cert_v),
                        outdir, coqc, flags)
        print("RESULT:", "PASS (Coq kernel accepted the correspondence)"
              if rc == 0 else "FAIL")
        return rc
    except (OSError, GenError, cc_mod.ParseError) as exc:
        print(f"ERROR: {exc}", file=sys.stderr)
        return 2


if __name__ == "__main__":
    sys.exit(main(sys.argv))
